/* tslint:disable */
/* eslint-disable */
/**
 * Green Space Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: develop
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionInfo } from './VersionInfo';
import {
    VersionInfoFromJSON,
    VersionInfoFromJSONTyped,
    VersionInfoToJSON,
    VersionInfoToJSONTyped,
} from './VersionInfo';
import type { MapInfo } from './MapInfo';
import {
    MapInfoFromJSON,
    MapInfoFromJSONTyped,
    MapInfoToJSON,
    MapInfoToJSONTyped,
} from './MapInfo';
import type { GitInfo } from './GitInfo';
import {
    GitInfoFromJSON,
    GitInfoFromJSONTyped,
    GitInfoToJSON,
    GitInfoToJSONTyped,
} from './GitInfo';

/**
 * 
 * @export
 * @interface AppInfo
 */
export interface AppInfo {
    /**
     * 
     * @type {string}
     * @memberof AppInfo
     */
    buildTime: string;
    /**
     * 
     * @type {GitInfo}
     * @memberof AppInfo
     */
    git: GitInfo;
    /**
     * 
     * @type {string}
     * @memberof AppInfo
     */
    goVersion: string;
    /**
     * 
     * @type {MapInfo}
     * @memberof AppInfo
     */
    map: MapInfo;
    /**
     * 
     * @type {string}
     * @memberof AppInfo
     */
    version: string;
    /**
     * 
     * @type {VersionInfo}
     * @memberof AppInfo
     */
    versionInfo: VersionInfo;
}

/**
 * Check if a given object implements the AppInfo interface.
 */
export function instanceOfAppInfo(value: object): value is AppInfo {
    if (!('buildTime' in value) || value['buildTime'] === undefined) return false;
    if (!('git' in value) || value['git'] === undefined) return false;
    if (!('goVersion' in value) || value['goVersion'] === undefined) return false;
    if (!('map' in value) || value['map'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('versionInfo' in value) || value['versionInfo'] === undefined) return false;
    return true;
}

export function AppInfoFromJSON(json: any): AppInfo {
    return AppInfoFromJSONTyped(json, false);
}

export function AppInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'buildTime': json['buildTime'],
        'git': GitInfoFromJSON(json['git']),
        'goVersion': json['goVersion'],
        'map': MapInfoFromJSON(json['map']),
        'version': json['version'],
        'versionInfo': VersionInfoFromJSON(json['versionInfo']),
    };
}

export function AppInfoToJSON(json: any): AppInfo {
    return AppInfoToJSONTyped(json, false);
}

export function AppInfoToJSONTyped(value?: AppInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buildTime': value['buildTime'],
        'git': GitInfoToJSON(value['git']),
        'goVersion': value['goVersion'],
        'map': MapInfoToJSON(value['map']),
        'version': value['version'],
        'versionInfo': VersionInfoToJSON(value['versionInfo']),
    };
}

