/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DbPoolStatsResponse
 */
export interface DbPoolStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof DbPoolStatsResponse
     */
    active: number;
    /**
     * 
     * @type {number}
     * @memberof DbPoolStatsResponse
     */
    idle: number;
    /**
     * 
     * @type {number}
     * @memberof DbPoolStatsResponse
     */
    max: number;
    /**
     * 
     * @type {number}
     * @memberof DbPoolStatsResponse
     */
    size: number;
}

/**
 * Check if a given object implements the DbPoolStatsResponse interface.
 */
export function instanceOfDbPoolStatsResponse(value: object): value is DbPoolStatsResponse {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('idle' in value) || value['idle'] === undefined) return false;
    if (!('max' in value) || value['max'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function DbPoolStatsResponseFromJSON(json: any): DbPoolStatsResponse {
    return DbPoolStatsResponseFromJSONTyped(json, false);
}

export function DbPoolStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DbPoolStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'idle': json['idle'],
        'max': json['max'],
        'size': json['size'],
    };
}

export function DbPoolStatsResponseToJSON(json: any): DbPoolStatsResponse {
    return DbPoolStatsResponseToJSONTyped(json, false);
}

export function DbPoolStatsResponseToJSONTyped(value?: DbPoolStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'idle': value['idle'],
        'max': value['max'],
        'size': value['size'],
    };
}

