/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-1237e5c-stage
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoJsonFeature } from './GeoJsonFeature';
import {
    GeoJsonFeatureFromJSON,
    GeoJsonFeatureFromJSONTyped,
    GeoJsonFeatureToJSON,
    GeoJsonFeatureToJSONTyped,
} from './GeoJsonFeature';
import type { GeoJsonType } from './GeoJsonType';
import {
    GeoJsonTypeFromJSON,
    GeoJsonTypeFromJSONTyped,
    GeoJsonTypeToJSON,
    GeoJsonTypeToJSONTyped,
} from './GeoJsonType';
import type { GeoJSONMetadata } from './GeoJSONMetadata';
import {
    GeoJSONMetadataFromJSON,
    GeoJSONMetadataFromJSONTyped,
    GeoJSONMetadataToJSON,
    GeoJSONMetadataToJSONTyped,
} from './GeoJSONMetadata';

/**
 * 
 * @export
 * @interface GeoJson
 */
export interface GeoJson {
    /**
     * 
     * @type {Array<number>}
     * @memberof GeoJson
     */
    bbox: Array<number>;
    /**
     * 
     * @type {Array<GeoJsonFeature>}
     * @memberof GeoJson
     */
    features: Array<GeoJsonFeature>;
    /**
     * 
     * @type {GeoJSONMetadata}
     * @memberof GeoJson
     */
    metadata: GeoJSONMetadata;
    /**
     * 
     * @type {GeoJsonType}
     * @memberof GeoJson
     */
    type: GeoJsonType;
}



/**
 * Check if a given object implements the GeoJson interface.
 */
export function instanceOfGeoJson(value: object): value is GeoJson {
    if (!('bbox' in value) || value['bbox'] === undefined) return false;
    if (!('features' in value) || value['features'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function GeoJsonFromJSON(json: any): GeoJson {
    return GeoJsonFromJSONTyped(json, false);
}

export function GeoJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJson {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'],
        'features': ((json['features'] as Array<any>).map(GeoJsonFeatureFromJSON)),
        'metadata': GeoJSONMetadataFromJSON(json['metadata']),
        'type': GeoJsonTypeFromJSON(json['type']),
    };
}

export function GeoJsonToJSON(json: any): GeoJson {
    return GeoJsonToJSONTyped(json, false);
}

export function GeoJsonToJSONTyped(value?: GeoJson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': value['bbox'],
        'features': ((value['features'] as Array<any>).map(GeoJsonFeatureToJSON)),
        'metadata': GeoJSONMetadataToJSON(value['metadata']),
        'type': GeoJsonTypeToJSON(value['type']),
    };
}

