/* tslint:disable */
/* eslint-disable */
/**
 * Green Space Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: develop
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoJSONType } from './GeoJSONType';
import {
    GeoJSONTypeFromJSON,
    GeoJSONTypeFromJSONTyped,
    GeoJSONTypeToJSON,
    GeoJSONTypeToJSONTyped,
} from './GeoJSONType';
import type { GeoJSONFeature } from './GeoJSONFeature';
import {
    GeoJSONFeatureFromJSON,
    GeoJSONFeatureFromJSONTyped,
    GeoJSONFeatureToJSON,
    GeoJSONFeatureToJSONTyped,
} from './GeoJSONFeature';
import type { GeoJSONMetadata } from './GeoJSONMetadata';
import {
    GeoJSONMetadataFromJSON,
    GeoJSONMetadataFromJSONTyped,
    GeoJSONMetadataToJSON,
    GeoJSONMetadataToJSONTyped,
} from './GeoJSONMetadata';

/**
 * 
 * @export
 * @interface GeoJSON
 */
export interface GeoJSON {
    /**
     * 
     * @type {Array<number>}
     * @memberof GeoJSON
     */
    bbox: Array<number>;
    /**
     * 
     * @type {Array<GeoJSONFeature>}
     * @memberof GeoJSON
     */
    features: Array<GeoJSONFeature>;
    /**
     * 
     * @type {GeoJSONMetadata}
     * @memberof GeoJSON
     */
    metadata: GeoJSONMetadata;
    /**
     * 
     * @type {GeoJSONType}
     * @memberof GeoJSON
     */
    type: GeoJSONType;
}



/**
 * Check if a given object implements the GeoJSON interface.
 */
export function instanceOfGeoJSON(value: object): value is GeoJSON {
    if (!('bbox' in value) || value['bbox'] === undefined) return false;
    if (!('features' in value) || value['features'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function GeoJSONFromJSON(json: any): GeoJSON {
    return GeoJSONFromJSONTyped(json, false);
}

export function GeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'],
        'features': ((json['features'] as Array<any>).map(GeoJSONFeatureFromJSON)),
        'metadata': GeoJSONMetadataFromJSON(json['metadata']),
        'type': GeoJSONTypeFromJSON(json['type']),
    };
}

export function GeoJSONToJSON(json: any): GeoJSON {
    return GeoJSONToJSONTyped(json, false);
}

export function GeoJSONToJSONTyped(value?: GeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': value['bbox'],
        'features': ((value['features'] as Array<any>).map(GeoJSONFeatureToJSON)),
        'metadata': GeoJSONMetadataToJSON(value['metadata']),
        'type': GeoJSONTypeToJSON(value['type']),
    };
}

