/* tslint:disable */
/* eslint-disable */
/**
 * Green Space Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: develop
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoJSONLocation } from './GeoJSONLocation';
import {
    GeoJSONLocationFromJSON,
    GeoJSONLocationFromJSONTyped,
    GeoJSONLocationToJSON,
    GeoJSONLocationToJSONTyped,
} from './GeoJSONLocation';

/**
 * 
 * @export
 * @interface GeoJSONMetadata
 */
export interface GeoJSONMetadata {
    /**
     * 
     * @type {GeoJSONLocation}
     * @memberof GeoJSONMetadata
     */
    endPoint: GeoJSONLocation;
    /**
     * 
     * @type {GeoJSONLocation}
     * @memberof GeoJSONMetadata
     */
    startPoint: GeoJSONLocation;
    /**
     * 
     * @type {GeoJSONLocation}
     * @memberof GeoJSONMetadata
     */
    wateringPoint: GeoJSONLocation;
}

/**
 * Check if a given object implements the GeoJSONMetadata interface.
 */
export function instanceOfGeoJSONMetadata(value: object): value is GeoJSONMetadata {
    if (!('endPoint' in value) || value['endPoint'] === undefined) return false;
    if (!('startPoint' in value) || value['startPoint'] === undefined) return false;
    if (!('wateringPoint' in value) || value['wateringPoint'] === undefined) return false;
    return true;
}

export function GeoJSONMetadataFromJSON(json: any): GeoJSONMetadata {
    return GeoJSONMetadataFromJSONTyped(json, false);
}

export function GeoJSONMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJSONMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'endPoint': GeoJSONLocationFromJSON(json['end_point']),
        'startPoint': GeoJSONLocationFromJSON(json['start_point']),
        'wateringPoint': GeoJSONLocationFromJSON(json['watering_point']),
    };
}

export function GeoJSONMetadataToJSON(json: any): GeoJSONMetadata {
    return GeoJSONMetadataToJSONTyped(json, false);
}

export function GeoJSONMetadataToJSONTyped(value?: GeoJSONMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_point': GeoJSONLocationToJSON(value['endPoint']),
        'start_point': GeoJSONLocationToJSON(value['startPoint']),
        'watering_point': GeoJSONLocationToJSON(value['wateringPoint']),
    };
}

