/* tslint:disable */
/* eslint-disable */
/**
 * Green Space Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: develop
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeoJSONLocation
 */
export interface GeoJSONLocation {
    /**
     * 
     * @type {object}
     * @memberof GeoJSONLocation
     */
    coordinate?: object;
}

/**
 * Check if a given object implements the GeoJSONLocation interface.
 */
export function instanceOfGeoJSONLocation(value: object): value is GeoJSONLocation {
    return true;
}

export function GeoJSONLocationFromJSON(json: any): GeoJSONLocation {
    return GeoJSONLocationFromJSONTyped(json, false);
}

export function GeoJSONLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeoJSONLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinate': json['coordinate'] == null ? undefined : json['coordinate'],
    };
}

export function GeoJSONLocationToJSON(json: any): GeoJSONLocation {
    return GeoJSONLocationToJSONTyped(json, false);
}

export function GeoJSONLocationToJSONTyped(value?: GeoJSONLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coordinate': value['coordinate'],
    };
}

