/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-45-gbbcdc5fa-dirty
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitInfo
 */
export interface GitInfo {
    /**
     * 
     * @type {string}
     * @memberof GitInfo
     */
    branch: string;
    /**
     * 
     * @type {string}
     * @memberof GitInfo
     */
    commit: string;
    /**
     * 
     * @type {string}
     * @memberof GitInfo
     */
    repository: string;
}

/**
 * Check if a given object implements the GitInfo interface.
 */
export function instanceOfGitInfo(value: object): value is GitInfo {
    if (!('branch' in value) || value['branch'] === undefined) return false;
    if (!('commit' in value) || value['commit'] === undefined) return false;
    if (!('repository' in value) || value['repository'] === undefined) return false;
    return true;
}

export function GitInfoFromJSON(json: any): GitInfo {
    return GitInfoFromJSONTyped(json, false);
}

export function GitInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'],
        'commit': json['commit'],
        'repository': json['repository'],
    };
}

export function GitInfoToJSON(json: any): GitInfo {
    return GitInfoToJSONTyped(json, false);
}

export function GitInfoToJSONTyped(value?: GitInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch': value['branch'],
        'commit': value['commit'],
        'repository': value['repository'],
    };
}

