/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-1237e5c-stage
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HTTPError
 */
export interface HTTPError {
    /**
     * 
     * @type {number}
     * @memberof HTTPError
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof HTTPError
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof HTTPError
     */
    method: string;
    /**
     * 
     * @type {string}
     * @memberof HTTPError
     */
    path: string;
}

/**
 * Check if a given object implements the HTTPError interface.
 */
export function instanceOfHTTPError(value: object): value is HTTPError {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function HTTPErrorFromJSON(json: any): HTTPError {
    return HTTPErrorFromJSONTyped(json, false);
}

export function HTTPErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): HTTPError {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'error': json['error'],
        'method': json['method'],
        'path': json['path'],
    };
}

export function HTTPErrorToJSON(json: any): HTTPError {
    return HTTPErrorToJSONTyped(json, false);
}

export function HTTPErrorToJSONTyped(value?: HTTPError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'method': value['method'],
        'path': value['path'],
    };
}

