/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SensorCoordinate } from './SensorCoordinate';
import {
    SensorCoordinateFromJSON,
    SensorCoordinateFromJSONTyped,
    SensorCoordinateToJSON,
    SensorCoordinateToJSONTyped,
} from './SensorCoordinate';
import type { SensorTypeResponse } from './SensorTypeResponse';
import {
    SensorTypeResponseFromJSON,
    SensorTypeResponseFromJSONTyped,
    SensorTypeResponseToJSON,
    SensorTypeResponseToJSONTyped,
} from './SensorTypeResponse';
import type { LorawanInfoResponse } from './LorawanInfoResponse';
import {
    LorawanInfoResponseFromJSON,
    LorawanInfoResponseFromJSONTyped,
    LorawanInfoResponseToJSON,
    LorawanInfoResponseToJSONTyped,
} from './LorawanInfoResponse';
import type { SensorDataResponse } from './SensorDataResponse';
import {
    SensorDataResponseFromJSON,
    SensorDataResponseFromJSONTyped,
    SensorDataResponseToJSON,
    SensorDataResponseToJSONTyped,
} from './SensorDataResponse';
import type { SensorModelSummaryResponse } from './SensorModelSummaryResponse';
import {
    SensorModelSummaryResponseFromJSON,
    SensorModelSummaryResponseFromJSONTyped,
    SensorModelSummaryResponseToJSON,
    SensorModelSummaryResponseToJSONTyped,
} from './SensorModelSummaryResponse';
import type { SensorStatus } from './SensorStatus';
import {
    SensorStatusFromJSON,
    SensorStatusFromJSONTyped,
    SensorStatusToJSON,
    SensorStatusToJSONTyped,
} from './SensorStatus';

/**
 * A LoRaWAN sensor used for soil moisture monitoring.
 * @export
 * @interface ListResponseSensorResponseDataInner
 */
export interface ListResponseSensorResponseDataInner {
    /**
     * Provider-specific metadata as a JSON object.
     * @type {object}
     * @memberof ListResponseSensorResponseDataInner
     */
    additionalInformation?: object | null;
    /**
     * WGS-84 coordinate derived from the linked tree (if any).
     * @type {SensorCoordinate}
     * @memberof ListResponseSensorResponseDataInner
     */
    coordinate?: SensorCoordinate | null;
    /**
     * Timestamp when the sensor was registered (RFC 3339).
     * @type {string}
     * @memberof ListResponseSensorResponseDataInner
     */
    createdAt: string;
    /**
     * Unique sensor identifier (EUI).
     * @type {string}
     * @memberof ListResponseSensorResponseDataInner
     */
    id: string;
    /**
     * Most recent data payload from the sensor, if available.
     * @type {SensorDataResponse}
     * @memberof ListResponseSensorResponseDataInner
     */
    latestData?: SensorDataResponse | null;
    /**
     * Database id of the linked tree, if the sensor is currently attached.
     * @type {string}
     * @memberof ListResponseSensorResponseDataInner
     */
    linkedTreeId?: string | null;
    /**
     * LoRaWAN credentials (omits `app_key`).
     * @type {LorawanInfoResponse}
     * @memberof ListResponseSensorResponseDataInner
     */
    lorawan?: LorawanInfoResponse | null;
    /**
     * Sensor model summary (id + display name).
     * @type {SensorModelSummaryResponse}
     * @memberof ListResponseSensorResponseDataInner
     */
    model: SensorModelSummaryResponse;
    /**
     * Name of the data provider or integration (e.g. "ttn", "chirpstack").
     * @type {string}
     * @memberof ListResponseSensorResponseDataInner
     */
    provider?: string | null;
    /**
     * Bus/protocol class of the sensor.
     * @type {SensorTypeResponse}
     * @memberof ListResponseSensorResponseDataInner
     */
    sensorType: SensorTypeResponse;
    /**
     * Current connectivity status of the sensor.
     * @type {SensorStatus}
     * @memberof ListResponseSensorResponseDataInner
     */
    status: SensorStatus;
    /**
     * Timestamp when the sensor record was last updated (RFC 3339).
     * @type {string}
     * @memberof ListResponseSensorResponseDataInner
     */
    updatedAt: string;
}



/**
 * Check if a given object implements the ListResponseSensorResponseDataInner interface.
 */
export function instanceOfListResponseSensorResponseDataInner(value: object): value is ListResponseSensorResponseDataInner {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('sensorType' in value) || value['sensorType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ListResponseSensorResponseDataInnerFromJSON(json: any): ListResponseSensorResponseDataInner {
    return ListResponseSensorResponseDataInnerFromJSONTyped(json, false);
}

export function ListResponseSensorResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseSensorResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'coordinate': json['coordinate'] == null ? undefined : SensorCoordinateFromJSON(json['coordinate']),
        'createdAt': json['created_at'],
        'id': json['id'],
        'latestData': json['latest_data'] == null ? undefined : SensorDataResponseFromJSON(json['latest_data']),
        'linkedTreeId': json['linked_tree_id'] == null ? undefined : json['linked_tree_id'],
        'lorawan': json['lorawan'] == null ? undefined : LorawanInfoResponseFromJSON(json['lorawan']),
        'model': SensorModelSummaryResponseFromJSON(json['model']),
        'provider': json['provider'] == null ? undefined : json['provider'],
        'sensorType': SensorTypeResponseFromJSON(json['sensor_type']),
        'status': SensorStatusFromJSON(json['status']),
        'updatedAt': json['updated_at'],
    };
}

export function ListResponseSensorResponseDataInnerToJSON(json: any): ListResponseSensorResponseDataInner {
    return ListResponseSensorResponseDataInnerToJSONTyped(json, false);
}

export function ListResponseSensorResponseDataInnerToJSONTyped(value?: ListResponseSensorResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'coordinate': SensorCoordinateToJSON(value['coordinate']),
        'created_at': value['createdAt'],
        'id': value['id'],
        'latest_data': SensorDataResponseToJSON(value['latestData']),
        'linked_tree_id': value['linkedTreeId'],
        'lorawan': LorawanInfoResponseToJSON(value['lorawan']),
        'model': SensorModelSummaryResponseToJSON(value['model']),
        'provider': value['provider'],
        'sensor_type': SensorTypeResponseToJSON(value['sensorType']),
        'status': SensorStatusToJSON(value['status']),
        'updated_at': value['updatedAt'],
    };
}

