/* tslint:disable */
/* eslint-disable */
/**
 * Green Space Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: develop
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginTokenRequest
 */
export interface LoginTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof LoginTokenRequest
     */
    code: string;
}

/**
 * Check if a given object implements the LoginTokenRequest interface.
 */
export function instanceOfLoginTokenRequest(value: object): value is LoginTokenRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function LoginTokenRequestFromJSON(json: any): LoginTokenRequest {
    return LoginTokenRequestFromJSONTyped(json, false);
}

export function LoginTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function LoginTokenRequestToJSON(json: any): LoginTokenRequest {
    return LoginTokenRequestToJSONTyped(json, false);
}

export function LoginTokenRequestToJSONTyped(value?: LoginTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

