/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapInfoResponse
 */
export interface MapInfoResponse {
    /**
     * Absent where the map may be panned anywhere. The instance default
     * always carries one; an organization may choose to drop the limit.
     * @type {Array<number>}
     * @memberof MapInfoResponse
     */
    bbox?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof MapInfoResponse
     */
    center: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof MapInfoResponse
     */
    maxZoom?: number | null;
    /**
     * The zoom range the map is held to, absent together with `bbox`.
     * @type {number}
     * @memberof MapInfoResponse
     */
    minZoom?: number | null;
}

/**
 * Check if a given object implements the MapInfoResponse interface.
 */
export function instanceOfMapInfoResponse(value: object): value is MapInfoResponse {
    if (!('center' in value) || value['center'] === undefined) return false;
    return true;
}

export function MapInfoResponseFromJSON(json: any): MapInfoResponse {
    return MapInfoResponseFromJSONTyped(json, false);
}

export function MapInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'] == null ? undefined : json['bbox'],
        'center': json['center'],
        'maxZoom': json['max_zoom'] == null ? undefined : json['max_zoom'],
        'minZoom': json['min_zoom'] == null ? undefined : json['min_zoom'],
    };
}

export function MapInfoResponseToJSON(json: any): MapInfoResponse {
    return MapInfoResponseToJSONTyped(json, false);
}

export function MapInfoResponseToJSONTyped(value?: MapInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': value['bbox'],
        'center': value['center'],
        'max_zoom': value['maxZoom'],
        'min_zoom': value['minZoom'],
    };
}

