/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MapViewDto } from './MapViewDto';
import {
    MapViewDtoFromJSON,
    MapViewDtoFromJSONTyped,
    MapViewDtoToJSON,
    MapViewDtoToJSONTyped,
} from './MapViewDto';

/**
 * Three states per field. Absent means unchanged, `null` means go back to
 * inheriting, a value means set it.
 * @export
 * @interface OrganizationSettingsUpdateRequest
 */
export interface OrganizationSettingsUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof OrganizationSettingsUpdateRequest
     */
    defectStreak?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationSettingsUpdateRequest
     */
    descendantsMayOverride?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof OrganizationSettingsUpdateRequest
     */
    justWateredTtlSecs?: number | null;
    /**
     * 
     * @type {MapViewDto}
     * @memberof OrganizationSettingsUpdateRequest
     */
    mapView?: MapViewDto | null;
    /**
     * 
     * @type {number}
     * @memberof OrganizationSettingsUpdateRequest
     */
    sensorOfflineAfterSecs?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OrganizationSettingsUpdateRequest
     */
    waterDemand?: number | null;
}

/**
 * Check if a given object implements the OrganizationSettingsUpdateRequest interface.
 */
export function instanceOfOrganizationSettingsUpdateRequest(value: object): value is OrganizationSettingsUpdateRequest {
    return true;
}

export function OrganizationSettingsUpdateRequestFromJSON(json: any): OrganizationSettingsUpdateRequest {
    return OrganizationSettingsUpdateRequestFromJSONTyped(json, false);
}

export function OrganizationSettingsUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationSettingsUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'defectStreak': json['defect_streak'] == null ? undefined : json['defect_streak'],
        'descendantsMayOverride': json['descendants_may_override'] == null ? undefined : json['descendants_may_override'],
        'justWateredTtlSecs': json['just_watered_ttl_secs'] == null ? undefined : json['just_watered_ttl_secs'],
        'mapView': json['map_view'] == null ? undefined : MapViewDtoFromJSON(json['map_view']),
        'sensorOfflineAfterSecs': json['sensor_offline_after_secs'] == null ? undefined : json['sensor_offline_after_secs'],
        'waterDemand': json['water_demand'] == null ? undefined : json['water_demand'],
    };
}

export function OrganizationSettingsUpdateRequestToJSON(json: any): OrganizationSettingsUpdateRequest {
    return OrganizationSettingsUpdateRequestToJSONTyped(json, false);
}

export function OrganizationSettingsUpdateRequestToJSONTyped(value?: OrganizationSettingsUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defect_streak': value['defectStreak'],
        'descendants_may_override': value['descendantsMayOverride'],
        'just_watered_ttl_secs': value['justWateredTtlSecs'],
        'map_view': MapViewDtoToJSON(value['mapView']),
        'sensor_offline_after_secs': value['sensorOfflineAfterSecs'],
        'water_demand': value['waterDemand'],
    };
}

