/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for renaming an organization.
 * @export
 * @interface OrganizationRenameRequest
 */
export interface OrganizationRenameRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganizationRenameRequest
     */
    name: string;
}

/**
 * Check if a given object implements the OrganizationRenameRequest interface.
 */
export function instanceOfOrganizationRenameRequest(value: object): value is OrganizationRenameRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizationRenameRequestFromJSON(json: any): OrganizationRenameRequest {
    return OrganizationRenameRequestFromJSONTyped(json, false);
}

export function OrganizationRenameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationRenameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function OrganizationRenameRequestToJSON(json: any): OrganizationRenameRequest {
    return OrganizationRenameRequestToJSONTyped(json, false);
}

export function OrganizationRenameRequestToJSONTyped(value?: OrganizationRenameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

