/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-44-g746440f4-dirty
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PluginAuth
 */
export interface PluginAuth {
    /**
     * 
     * @type {string}
     * @memberof PluginAuth
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof PluginAuth
     */
    clientSecret: string;
}

/**
 * Check if a given object implements the PluginAuth interface.
 */
export function instanceOfPluginAuth(value: object): value is PluginAuth {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('clientSecret' in value) || value['clientSecret'] === undefined) return false;
    return true;
}

export function PluginAuthFromJSON(json: any): PluginAuth {
    return PluginAuthFromJSONTyped(json, false);
}

export function PluginAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginAuth {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'clientSecret': json['client_secret'],
    };
}

export function PluginAuthToJSON(json: any): PluginAuth {
    return PluginAuthToJSONTyped(json, false);
}

export function PluginAuthToJSONTyped(value?: PluginAuth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
    };
}

