/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-44-g746440f4-dirty
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginAuth } from './PluginAuth';
import {
    PluginAuthFromJSON,
    PluginAuthFromJSONTyped,
    PluginAuthToJSON,
    PluginAuthToJSONTyped,
} from './PluginAuth';

/**
 * 
 * @export
 * @interface PluginRegisterRequest
 */
export interface PluginRegisterRequest {
    /**
     * 
     * @type {PluginAuth}
     * @memberof PluginRegisterRequest
     */
    auth: PluginAuth;
    /**
     * 
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof PluginRegisterRequest
     */
    version: string;
}

/**
 * Check if a given object implements the PluginRegisterRequest interface.
 */
export function instanceOfPluginRegisterRequest(value: object): value is PluginRegisterRequest {
    if (!('auth' in value) || value['auth'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PluginRegisterRequestFromJSON(json: any): PluginRegisterRequest {
    return PluginRegisterRequestFromJSONTyped(json, false);
}

export function PluginRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'auth': PluginAuthFromJSON(json['auth']),
        'description': json['description'],
        'name': json['name'],
        'path': json['path'],
        'slug': json['slug'],
        'version': json['version'],
    };
}

export function PluginRegisterRequestToJSON(json: any): PluginRegisterRequest {
    return PluginRegisterRequestToJSONTyped(json, false);
}

export function PluginRegisterRequestToJSONTyped(value?: PluginRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auth': PluginAuthToJSON(value['auth']),
        'description': value['description'],
        'name': value['name'],
        'path': value['path'],
        'slug': value['slug'],
        'version': value['version'],
    };
}

