/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProcessStatsResponse
 */
export interface ProcessStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof ProcessStatsResponse
     */
    threads: number;
    /**
     * 
     * @type {number}
     * @memberof ProcessStatsResponse
     */
    uptimeSeconds: number;
}

/**
 * Check if a given object implements the ProcessStatsResponse interface.
 */
export function instanceOfProcessStatsResponse(value: object): value is ProcessStatsResponse {
    if (!('threads' in value) || value['threads'] === undefined) return false;
    if (!('uptimeSeconds' in value) || value['uptimeSeconds'] === undefined) return false;
    return true;
}

export function ProcessStatsResponseFromJSON(json: any): ProcessStatsResponse {
    return ProcessStatsResponseFromJSONTyped(json, false);
}

export function ProcessStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'threads': json['threads'],
        'uptimeSeconds': json['uptimeSeconds'],
    };
}

export function ProcessStatsResponseToJSON(json: any): ProcessStatsResponse {
    return ProcessStatsResponseToJSONTyped(json, false);
}

export function ProcessStatsResponseToJSONTyped(value?: ProcessStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'threads': value['threads'],
        'uptimeSeconds': value['uptimeSeconds'],
    };
}

