/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v1.2.0-37-g1c5af7f8-stage
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteRequest
 */
export interface RouteRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof RouteRequest
     */
    clusterIds: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof RouteRequest
     */
    trailerId?: number;
    /**
     * 
     * @type {number}
     * @memberof RouteRequest
     */
    transporterId: number;
}

/**
 * Check if a given object implements the RouteRequest interface.
 */
export function instanceOfRouteRequest(value: object): value is RouteRequest {
    if (!('clusterIds' in value) || value['clusterIds'] === undefined) return false;
    if (!('transporterId' in value) || value['transporterId'] === undefined) return false;
    return true;
}

export function RouteRequestFromJSON(json: any): RouteRequest {
    return RouteRequestFromJSONTyped(json, false);
}

export function RouteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clusterIds': json['cluster_ids'],
        'trailerId': json['trailer_id'] == null ? undefined : json['trailer_id'],
        'transporterId': json['transporter_id'],
    };
}

export function RouteRequestToJSON(json: any): RouteRequest {
    return RouteRequestToJSONTyped(json, false);
}

export function RouteRequestToJSONTyped(value?: RouteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cluster_ids': value['clusterIds'],
        'trailer_id': value['trailerId'],
        'transporter_id': value['transporterId'],
    };
}

