/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-44-g746440f4-dirty
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WatermarkResponse } from './WatermarkResponse';
import {
    WatermarkResponseFromJSON,
    WatermarkResponseFromJSONTyped,
    WatermarkResponseToJSON,
    WatermarkResponseToJSONTyped,
} from './WatermarkResponse';

/**
 * 
 * @export
 * @interface SensorData
 */
export interface SensorData {
    /**
     * 
     * @type {number}
     * @memberof SensorData
     */
    battery: number;
    /**
     * 
     * @type {string}
     * @memberof SensorData
     */
    createdAt: string;
    /**
     * 
     * @type {number}
     * @memberof SensorData
     */
    humidity: number;
    /**
     * 
     * @type {number}
     * @memberof SensorData
     */
    temperature: number;
    /**
     * 
     * @type {string}
     * @memberof SensorData
     */
    updatedAt: string;
    /**
     * 
     * @type {Array<WatermarkResponse>}
     * @memberof SensorData
     */
    watermarks: Array<WatermarkResponse>;
}

/**
 * Check if a given object implements the SensorData interface.
 */
export function instanceOfSensorData(value: object): value is SensorData {
    if (!('battery' in value) || value['battery'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('humidity' in value) || value['humidity'] === undefined) return false;
    if (!('temperature' in value) || value['temperature'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('watermarks' in value) || value['watermarks'] === undefined) return false;
    return true;
}

export function SensorDataFromJSON(json: any): SensorData {
    return SensorDataFromJSONTyped(json, false);
}

export function SensorDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SensorData {
    if (json == null) {
        return json;
    }
    return {
        
        'battery': json['battery'],
        'createdAt': json['created_at'],
        'humidity': json['humidity'],
        'temperature': json['temperature'],
        'updatedAt': json['updated_at'],
        'watermarks': ((json['watermarks'] as Array<any>).map(WatermarkResponseFromJSON)),
    };
}

export function SensorDataToJSON(json: any): SensorData {
    return SensorDataToJSONTyped(json, false);
}

export function SensorDataToJSONTyped(value?: SensorData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'battery': value['battery'],
        'created_at': value['createdAt'],
        'humidity': value['humidity'],
        'temperature': value['temperature'],
        'updated_at': value['updatedAt'],
        'watermarks': ((value['watermarks'] as Array<any>).map(WatermarkResponseToJSON)),
    };
}

