/* tslint:disable */
/* eslint-disable */
/**
 * Green Space Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: develop
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceStatus
 */
export interface ServiceStatus {
    /**
     * 
     * @type {boolean}
     * @memberof ServiceStatus
     */
    enabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceStatus
     */
    healthy: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceStatus
     */
    lastChecked?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceStatus
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceStatus
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceStatus
     */
    responseTimeMs?: number;
}

/**
 * Check if a given object implements the ServiceStatus interface.
 */
export function instanceOfServiceStatus(value: object): value is ServiceStatus {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('healthy' in value) || value['healthy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ServiceStatusFromJSON(json: any): ServiceStatus {
    return ServiceStatusFromJSONTyped(json, false);
}

export function ServiceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'healthy': json['healthy'],
        'lastChecked': json['lastChecked'] == null ? undefined : json['lastChecked'],
        'message': json['message'] == null ? undefined : json['message'],
        'name': json['name'],
        'responseTimeMs': json['responseTimeMs'] == null ? undefined : json['responseTimeMs'],
    };
}

export function ServiceStatusToJSON(json: any): ServiceStatus {
    return ServiceStatusToJSONTyped(json, false);
}

export function ServiceStatusToJSONTyped(value?: ServiceStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'healthy': value['healthy'],
        'lastChecked': value['lastChecked'],
        'message': value['message'],
        'name': value['name'],
        'responseTimeMs': value['responseTimeMs'],
    };
}

