/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-44-g746440f4-dirty
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerInfo
 */
export interface ServerInfo {
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    arch: string;
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    hostname: string;
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    _interface: string;
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    ip: string;
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    os: string;
    /**
     * 
     * @type {number}
     * @memberof ServerInfo
     */
    port: number;
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    uptime: string;
    /**
     * 
     * @type {string}
     * @memberof ServerInfo
     */
    url: string;
}

/**
 * Check if a given object implements the ServerInfo interface.
 */
export function instanceOfServerInfo(value: object): value is ServerInfo {
    if (!('arch' in value) || value['arch'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('_interface' in value) || value['_interface'] === undefined) return false;
    if (!('ip' in value) || value['ip'] === undefined) return false;
    if (!('os' in value) || value['os'] === undefined) return false;
    if (!('port' in value) || value['port'] === undefined) return false;
    if (!('uptime' in value) || value['uptime'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ServerInfoFromJSON(json: any): ServerInfo {
    return ServerInfoFromJSONTyped(json, false);
}

export function ServerInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'arch': json['arch'],
        'hostname': json['hostname'],
        '_interface': json['interface'],
        'ip': json['ip'],
        'os': json['os'],
        'port': json['port'],
        'uptime': json['uptime'],
        'url': json['url'],
    };
}

export function ServerInfoToJSON(json: any): ServerInfo {
    return ServerInfoToJSONTyped(json, false);
}

export function ServerInfoToJSONTyped(value?: ServerInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arch': value['arch'],
        'hostname': value['hostname'],
        'interface': value['_interface'],
        'ip': value['ip'],
        'os': value['os'],
        'port': value['port'],
        'uptime': value['uptime'],
        'url': value['url'],
    };
}

