/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Health and availability status of an individual backend service.
 * @export
 * @interface ServiceStatusResponse
 */
export interface ServiceStatusResponse {
    /**
     * Whether the service is enabled in the configuration.
     * @type {boolean}
     * @memberof ServiceStatusResponse
     */
    enabled: boolean;
    /**
     * Whether the last health check succeeded.
     * @type {boolean}
     * @memberof ServiceStatusResponse
     */
    healthy: boolean;
    /**
     * ISO 8601 timestamp of the last health check.
     * @type {string}
     * @memberof ServiceStatusResponse
     */
    lastChecked?: string | null;
    /**
     * Human-readable status message.
     * @type {string}
     * @memberof ServiceStatusResponse
     */
    message?: string | null;
    /**
     * Name of the service (e.g. "database", "s3", "routing").
     * @type {string}
     * @memberof ServiceStatusResponse
     */
    name: string;
    /**
     * Response time of the last health check in milliseconds.
     * @type {number}
     * @memberof ServiceStatusResponse
     */
    responseTimeMs?: number | null;
}

/**
 * Check if a given object implements the ServiceStatusResponse interface.
 */
export function instanceOfServiceStatusResponse(value: object): value is ServiceStatusResponse {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('healthy' in value) || value['healthy'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ServiceStatusResponseFromJSON(json: any): ServiceStatusResponse {
    return ServiceStatusResponseFromJSONTyped(json, false);
}

export function ServiceStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'healthy': json['healthy'],
        'lastChecked': json['lastChecked'] == null ? undefined : json['lastChecked'],
        'message': json['message'] == null ? undefined : json['message'],
        'name': json['name'],
        'responseTimeMs': json['responseTimeMs'] == null ? undefined : json['responseTimeMs'],
    };
}

export function ServiceStatusResponseToJSON(json: any): ServiceStatusResponse {
    return ServiceStatusResponseToJSONTyped(json, false);
}

export function ServiceStatusResponseToJSONTyped(value?: ServiceStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'healthy': value['healthy'],
        'lastChecked': value['lastChecked'],
        'message': value['message'],
        'name': value['name'],
        'responseTimeMs': value['responseTimeMs'],
    };
}

