/* tslint:disable */
/* eslint-disable */
/**
 * Green Space Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: develop
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SharedGeoJSONLocation } from './SharedGeoJSONLocation';
import {
    SharedGeoJSONLocationFromJSON,
    SharedGeoJSONLocationFromJSONTyped,
    SharedGeoJSONLocationToJSON,
    SharedGeoJSONLocationToJSONTyped,
} from './SharedGeoJSONLocation';

/**
 * 
 * @export
 * @interface SharedGeoJSONMetadata
 */
export interface SharedGeoJSONMetadata {
    /**
     * 
     * @type {SharedGeoJSONLocation}
     * @memberof SharedGeoJSONMetadata
     */
    endPoint?: SharedGeoJSONLocation;
    /**
     * 
     * @type {SharedGeoJSONLocation}
     * @memberof SharedGeoJSONMetadata
     */
    startPoint?: SharedGeoJSONLocation;
    /**
     * 
     * @type {SharedGeoJSONLocation}
     * @memberof SharedGeoJSONMetadata
     */
    wateringPoint?: SharedGeoJSONLocation;
}

/**
 * Check if a given object implements the SharedGeoJSONMetadata interface.
 */
export function instanceOfSharedGeoJSONMetadata(value: object): value is SharedGeoJSONMetadata {
    return true;
}

export function SharedGeoJSONMetadataFromJSON(json: any): SharedGeoJSONMetadata {
    return SharedGeoJSONMetadataFromJSONTyped(json, false);
}

export function SharedGeoJSONMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedGeoJSONMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'endPoint': json['endPoint'] == null ? undefined : SharedGeoJSONLocationFromJSON(json['endPoint']),
        'startPoint': json['startPoint'] == null ? undefined : SharedGeoJSONLocationFromJSON(json['startPoint']),
        'wateringPoint': json['wateringPoint'] == null ? undefined : SharedGeoJSONLocationFromJSON(json['wateringPoint']),
    };
}

export function SharedGeoJSONMetadataToJSON(json: any): SharedGeoJSONMetadata {
    return SharedGeoJSONMetadataToJSONTyped(json, false);
}

export function SharedGeoJSONMetadataToJSONTyped(value?: SharedGeoJSONMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endPoint': SharedGeoJSONLocationToJSON(value['endPoint']),
        'startPoint': SharedGeoJSONLocationToJSON(value['startPoint']),
        'wateringPoint': SharedGeoJSONLocationToJSON(value['wateringPoint']),
    };
}

