/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for sharing a resource with a descendant organization.
 * @export
 * @interface ShareRequest
 */
export interface ShareRequest {
    /**
     * 
     * @type {string}
     * @memberof ShareRequest
     */
    organizationId: string;
}

/**
 * Check if a given object implements the ShareRequest interface.
 */
export function instanceOfShareRequest(value: object): value is ShareRequest {
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    return true;
}

export function ShareRequestFromJSON(json: any): ShareRequest {
    return ShareRequestFromJSONTyped(json, false);
}

export function ShareRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organization_id'],
    };
}

export function ShareRequestToJSON(json: any): ShareRequest {
    return ShareRequestToJSONTyped(json, false);
}

export function ShareRequestToJSONTyped(value?: ShareRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organizationId'],
    };
}

