/* tslint:disable */
/* eslint-disable */
/**
 * Green Space Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: develop
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SharedGeoJSONGeometry } from './SharedGeoJSONGeometry';
import {
    SharedGeoJSONGeometryFromJSON,
    SharedGeoJSONGeometryFromJSONTyped,
    SharedGeoJSONGeometryToJSON,
    SharedGeoJSONGeometryToJSONTyped,
} from './SharedGeoJSONGeometry';
import type { SharedGeoJSONType } from './SharedGeoJSONType';
import {
    SharedGeoJSONTypeFromJSON,
    SharedGeoJSONTypeFromJSONTyped,
    SharedGeoJSONTypeToJSON,
    SharedGeoJSONTypeToJSONTyped,
} from './SharedGeoJSONType';

/**
 * 
 * @export
 * @interface SharedGeoJSONFeature
 */
export interface SharedGeoJSONFeature {
    /**
     * 
     * @type {Array<number>}
     * @memberof SharedGeoJSONFeature
     */
    bbox: Array<number>;
    /**
     * 
     * @type {SharedGeoJSONGeometry}
     * @memberof SharedGeoJSONFeature
     */
    geometry: SharedGeoJSONGeometry;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof SharedGeoJSONFeature
     */
    properties: { [key: string]: object; };
    /**
     * 
     * @type {SharedGeoJSONType}
     * @memberof SharedGeoJSONFeature
     */
    type: SharedGeoJSONType;
}



/**
 * Check if a given object implements the SharedGeoJSONFeature interface.
 */
export function instanceOfSharedGeoJSONFeature(value: object): value is SharedGeoJSONFeature {
    if (!('bbox' in value) || value['bbox'] === undefined) return false;
    if (!('geometry' in value) || value['geometry'] === undefined) return false;
    if (!('properties' in value) || value['properties'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function SharedGeoJSONFeatureFromJSON(json: any): SharedGeoJSONFeature {
    return SharedGeoJSONFeatureFromJSONTyped(json, false);
}

export function SharedGeoJSONFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharedGeoJSONFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'bbox': json['bbox'],
        'geometry': SharedGeoJSONGeometryFromJSON(json['geometry']),
        'properties': json['properties'],
        'type': SharedGeoJSONTypeFromJSON(json['type']),
    };
}

export function SharedGeoJSONFeatureToJSON(json: any): SharedGeoJSONFeature {
    return SharedGeoJSONFeatureToJSONTyped(json, false);
}

export function SharedGeoJSONFeatureToJSONTyped(value?: SharedGeoJSONFeature | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bbox': value['bbox'],
        'geometry': SharedGeoJSONGeometryToJSON(value['geometry']),
        'properties': value['properties'],
        'type': SharedGeoJSONTypeToJSON(value['type']),
    };
}

