/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for updating an existing tree.
 * @export
 * @interface TreeUpdateRequest
 */
export interface TreeUpdateRequest {
    /**
     * Provider-specific metadata as arbitrary JSON.
     * @type {object}
     * @memberof TreeUpdateRequest
     */
    additionalInformation?: object | null;
    /**
     * Additional notes or description.
     * @type {string}
     * @memberof TreeUpdateRequest
     */
    description: string;
    /**
     * Geographic latitude (WGS 84).
     * @type {number}
     * @memberof TreeUpdateRequest
     */
    latitude: number;
    /**
     * Geographic longitude (WGS 84).
     * @type {number}
     * @memberof TreeUpdateRequest
     */
    longitude: number;
    /**
     * Internal tree identification number.
     * @type {string}
     * @memberof TreeUpdateRequest
     */
    number: string;
    /**
     * Year the tree was planted.
     * @type {number}
     * @memberof TreeUpdateRequest
     */
    plantingYear: number;
    /**
     * Name of the data provider.
     * @type {string}
     * @memberof TreeUpdateRequest
     */
    provider?: string | null;
    /**
     * Sensor ID to link to this tree.
     * @type {string}
     * @memberof TreeUpdateRequest
     */
    sensorId?: string | null;
    /**
     * Tree species name.
     * @type {string}
     * @memberof TreeUpdateRequest
     */
    species: string;
    /**
     * Cluster ID to assign this tree to.
     * @type {number}
     * @memberof TreeUpdateRequest
     */
    treeClusterId?: number | null;
}

/**
 * Check if a given object implements the TreeUpdateRequest interface.
 */
export function instanceOfTreeUpdateRequest(value: object): value is TreeUpdateRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('plantingYear' in value) || value['plantingYear'] === undefined) return false;
    if (!('species' in value) || value['species'] === undefined) return false;
    return true;
}

export function TreeUpdateRequestFromJSON(json: any): TreeUpdateRequest {
    return TreeUpdateRequestFromJSONTyped(json, false);
}

export function TreeUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'description': json['description'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'number': json['number'],
        'plantingYear': json['planting_year'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'sensorId': json['sensor_id'] == null ? undefined : json['sensor_id'],
        'species': json['species'],
        'treeClusterId': json['tree_cluster_id'] == null ? undefined : json['tree_cluster_id'],
    };
}

export function TreeUpdateRequestToJSON(json: any): TreeUpdateRequest {
    return TreeUpdateRequestToJSONTyped(json, false);
}

export function TreeUpdateRequestToJSONTyped(value?: TreeUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'description': value['description'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'number': value['number'],
        'planting_year': value['plantingYear'],
        'provider': value['provider'],
        'sensor_id': value['sensorId'],
        'species': value['species'],
        'tree_cluster_id': value['treeClusterId'],
    };
}

