/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SensorResponse } from './SensorResponse';
import {
    SensorResponseFromJSON,
    SensorResponseFromJSONTyped,
    SensorResponseToJSON,
    SensorResponseToJSONTyped,
} from './SensorResponse';
import type { WateringStatus } from './WateringStatus';
import {
    WateringStatusFromJSON,
    WateringStatusFromJSONTyped,
    WateringStatusToJSON,
    WateringStatusToJSONTyped,
} from './WateringStatus';

/**
 * An individual tree managed by the system.
 * @export
 * @interface TreeResponse
 */
export interface TreeResponse {
    /**
     * Provider-specific metadata as arbitrary JSON.
     * @type {object}
     * @memberof TreeResponse
     */
    additionalInformation?: object | null;
    /**
     * Timestamp when the tree was registered (RFC 3339).
     * @type {string}
     * @memberof TreeResponse
     */
    createdAt: string;
    /**
     * Additional notes or description.
     * @type {string}
     * @memberof TreeResponse
     */
    description: string;
    /**
     * Unique tree identifier.
     * @type {number}
     * @memberof TreeResponse
     */
    id: number;
    /**
     * Timestamp of the last watering event (RFC 3339).
     * @type {string}
     * @memberof TreeResponse
     */
    lastWatered?: string | null;
    /**
     * Geographic latitude (WGS 84).
     * @type {number}
     * @memberof TreeResponse
     */
    latitude: number;
    /**
     * Geographic longitude (WGS 84).
     * @type {number}
     * @memberof TreeResponse
     */
    longitude: number;
    /**
     * Internal tree identification number.
     * @type {string}
     * @memberof TreeResponse
     */
    number: string;
    /**
     * Year the tree was planted.
     * @type {number}
     * @memberof TreeResponse
     */
    plantingYear: number;
    /**
     * Name of the data provider that created this tree.
     * @type {string}
     * @memberof TreeResponse
     */
    provider?: string | null;
    /**
     * Associated sensor, if linked.
     * @type {SensorResponse}
     * @memberof TreeResponse
     */
    sensor?: SensorResponse | null;
    /**
     * Tree species name.
     * @type {string}
     * @memberof TreeResponse
     */
    species: string;
    /**
     * ID of the cluster this tree belongs to, if assigned.
     * @type {number}
     * @memberof TreeResponse
     */
    treeClusterId?: number | null;
    /**
     * Timestamp of the last update (RFC 3339).
     * @type {string}
     * @memberof TreeResponse
     */
    updatedAt: string;
    /**
     * Current watering status based on sensor data.
     * @type {WateringStatus}
     * @memberof TreeResponse
     */
    wateringStatus: WateringStatus;
}



/**
 * Check if a given object implements the TreeResponse interface.
 */
export function instanceOfTreeResponse(value: object): value is TreeResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('plantingYear' in value) || value['plantingYear'] === undefined) return false;
    if (!('species' in value) || value['species'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('wateringStatus' in value) || value['wateringStatus'] === undefined) return false;
    return true;
}

export function TreeResponseFromJSON(json: any): TreeResponse {
    return TreeResponseFromJSONTyped(json, false);
}

export function TreeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TreeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'createdAt': json['created_at'],
        'description': json['description'],
        'id': json['id'],
        'lastWatered': json['last_watered'] == null ? undefined : json['last_watered'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'number': json['number'],
        'plantingYear': json['planting_year'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'sensor': json['sensor'] == null ? undefined : SensorResponseFromJSON(json['sensor']),
        'species': json['species'],
        'treeClusterId': json['tree_cluster_id'] == null ? undefined : json['tree_cluster_id'],
        'updatedAt': json['updated_at'],
        'wateringStatus': WateringStatusFromJSON(json['watering_status']),
    };
}

export function TreeResponseToJSON(json: any): TreeResponse {
    return TreeResponseToJSONTyped(json, false);
}

export function TreeResponseToJSONTyped(value?: TreeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'created_at': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'last_watered': value['lastWatered'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'number': value['number'],
        'planting_year': value['plantingYear'],
        'provider': value['provider'],
        'sensor': SensorResponseToJSON(value['sensor']),
        'species': value['species'],
        'tree_cluster_id': value['treeClusterId'],
        'updated_at': value['updatedAt'],
        'watering_status': WateringStatusToJSON(value['wateringStatus']),
    };
}

