/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-1237e5c-stage
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleType } from './VehicleType';
import {
    VehicleTypeFromJSON,
    VehicleTypeFromJSONTyped,
    VehicleTypeToJSON,
    VehicleTypeToJSONTyped,
} from './VehicleType';
import type { DrivingLicense } from './DrivingLicense';
import {
    DrivingLicenseFromJSON,
    DrivingLicenseFromJSONTyped,
    DrivingLicenseToJSON,
    DrivingLicenseToJSONTyped,
} from './DrivingLicense';
import type { VehicleStatus } from './VehicleStatus';
import {
    VehicleStatusFromJSON,
    VehicleStatusFromJSONTyped,
    VehicleStatusToJSON,
    VehicleStatusToJSONTyped,
} from './VehicleStatus';

/**
 * 
 * @export
 * @interface Vehicle
 */
export interface Vehicle {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Vehicle
     */
    additionalInformation?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    archivedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    description: string;
    /**
     * 
     * @type {DrivingLicense}
     * @memberof Vehicle
     */
    drivingLicense: DrivingLicense;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    height: number;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    length: number;
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    numberPlate: string;
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    provider?: string;
    /**
     * 
     * @type {VehicleStatus}
     * @memberof Vehicle
     */
    status: VehicleStatus;
    /**
     * 
     * @type {VehicleType}
     * @memberof Vehicle
     */
    type: VehicleType;
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    updatedAt: string;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    waterCapacity: number;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    weight: number;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    width: number;
}



/**
 * Check if a given object implements the Vehicle interface.
 */
export function instanceOfVehicle(value: object): value is Vehicle {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('drivingLicense' in value) || value['drivingLicense'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('numberPlate' in value) || value['numberPlate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('waterCapacity' in value) || value['waterCapacity'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    return true;
}

export function VehicleFromJSON(json: any): Vehicle {
    return VehicleFromJSONTyped(json, false);
}

export function VehicleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vehicle {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'archivedAt': json['archived_at'] == null ? undefined : json['archived_at'],
        'createdAt': json['created_at'],
        'description': json['description'],
        'drivingLicense': DrivingLicenseFromJSON(json['driving_license']),
        'height': json['height'],
        'id': json['id'],
        'length': json['length'],
        'model': json['model'],
        'numberPlate': json['number_plate'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'status': VehicleStatusFromJSON(json['status']),
        'type': VehicleTypeFromJSON(json['type']),
        'updatedAt': json['updated_at'],
        'waterCapacity': json['water_capacity'],
        'weight': json['weight'],
        'width': json['width'],
    };
}

export function VehicleToJSON(json: any): Vehicle {
    return VehicleToJSONTyped(json, false);
}

export function VehicleToJSONTyped(value?: Vehicle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'archived_at': value['archivedAt'],
        'created_at': value['createdAt'],
        'description': value['description'],
        'driving_license': DrivingLicenseToJSON(value['drivingLicense']),
        'height': value['height'],
        'id': value['id'],
        'length': value['length'],
        'model': value['model'],
        'number_plate': value['numberPlate'],
        'provider': value['provider'],
        'status': VehicleStatusToJSON(value['status']),
        'type': VehicleTypeToJSON(value['type']),
        'updated_at': value['updatedAt'],
        'water_capacity': value['waterCapacity'],
        'weight': value['weight'],
        'width': value['width'],
    };
}

