/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewTicketUserResponse
 */
export interface ViewTicketUserResponse {
    /**
     * 
     * @type {string}
     * @memberof ViewTicketUserResponse
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof ViewTicketUserResponse
     */
    id: string;
}

/**
 * Check if a given object implements the ViewTicketUserResponse interface.
 */
export function instanceOfViewTicketUserResponse(value: object): value is ViewTicketUserResponse {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ViewTicketUserResponseFromJSON(json: any): ViewTicketUserResponse {
    return ViewTicketUserResponseFromJSONTyped(json, false);
}

export function ViewTicketUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewTicketUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'],
        'id': json['id'],
    };
}

export function ViewTicketUserResponseToJSON(json: any): ViewTicketUserResponse {
    return ViewTicketUserResponseToJSONTyped(json, false);
}

export function ViewTicketUserResponseToJSONTyped(value?: ViewTicketUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'id': value['id'],
    };
}

