/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewTicketUserResponse } from './ViewTicketUserResponse';
import {
    ViewTicketUserResponseFromJSON,
    ViewTicketUserResponseFromJSONTyped,
    ViewTicketUserResponseToJSON,
    ViewTicketUserResponseToJSONTyped,
} from './ViewTicketUserResponse';

/**
 * 
 * @export
 * @interface ViewTicketRedeemResponse
 */
export interface ViewTicketRedeemResponse {
    /**
     * 
     * @type {string}
     * @memberof ViewTicketRedeemResponse
     */
    organizationId: string;
    /**
     * 
     * @type {ViewTicketUserResponse}
     * @memberof ViewTicketRedeemResponse
     */
    user: ViewTicketUserResponse;
}

/**
 * Check if a given object implements the ViewTicketRedeemResponse interface.
 */
export function instanceOfViewTicketRedeemResponse(value: object): value is ViewTicketRedeemResponse {
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function ViewTicketRedeemResponseFromJSON(json: any): ViewTicketRedeemResponse {
    return ViewTicketRedeemResponseFromJSONTyped(json, false);
}

export function ViewTicketRedeemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewTicketRedeemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organization_id'],
        'user': ViewTicketUserResponseFromJSON(json['user']),
    };
}

export function ViewTicketRedeemResponseToJSON(json: any): ViewTicketRedeemResponse {
    return ViewTicketRedeemResponseToJSONTyped(json, false);
}

export function ViewTicketRedeemResponseToJSONTyped(value?: ViewTicketRedeemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization_id': value['organizationId'],
        'user': ViewTicketUserResponseToJSON(value['user']),
    };
}

