# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: green-ecolution
spec:
  selector:
    app: green-ecolution
  type: ClusterIP
  ports:
  - name: green-ecolution
    protocol: TCP
    port: 80
    targetPort: 3000
---

