FROM alpine:3.23

ARG MIGRATION_WITH_SEED
ARG MIGRATION_WITH_DB_RESET

RUN apk add --no-cache bash curl
RUN curl -fsSL \
    https://raw.githubusercontent.com/pressly/goose/master/install.sh |\
    sh

COPY ./backend/internal/storage/postgres/migrations /migrations
COPY ./backend/internal/storage/postgres/seed /seed
COPY ./.docker/migrations/migration.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
