# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  template:
    spec:
      initContainers:
        - name: init-migrations
          image: backend-image
          imagePullPolicy: Always
          command: ["./migrate"]
          args: ["up"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
