# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-ecolution
  labels:
    app: green-ecolution
spec:
  template:
    spec:
      initContainers:
        - name: init-migrations
          image: green-ecolution-image
          imagePullPolicy: Always
          command: ["./migrate"]
          args: ["up"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
