#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    APP_MQTT__CLIENT_ID: ENC[AES256_GCM,data:k9SbsAOJcOlqUwV6UBcF0A==,iv:VM8n6RvZyrRnolGX99xmRZUQe511EM8RzFFiQmVzcpw=,tag:Q8uxO9IGQ3o/Yp/ZU+gB6A==,type:str]
    APP_MQTT__USERNAME: ENC[AES256_GCM,data:KmCVdE6HZYlznvhoYYuC7p8b+MhFeLVe,iv:njgZAp6OW15kPnB6hnU/2JIzs01trKFjCW4u5qy7oNg=,tag:AJiJcRn4Dn9kFb1Gg/bWJA==,type:str]
    APP_MQTT__PASSWORD: ENC[AES256_GCM,data:tqS3DUs+/t8ZZ/jaH7DWszJYGIAyLGnnHcixAVNa29JIwSyp8UI0UWXblxGzdBwfVZ8qFSOEwrA5RnaGZgtAXPZTKWCnjqdxoKTnZgOxcrBfzFctV5ZdACyoNux5zJDfTJcmihYjDGzKU7zfX3wzl9pm6MsXvpv5Ytbfj1t1A1/11an2,iv:coyKlmF2b0QcC8OPz9ZHw0uH0t4tKvvMVfZPIR2tQ0Y=,tag:IYMxWVNu7tjTJDJiBNPs0A==,type:str]
    APP_DATABASE__USERNAME: ENC[AES256_GCM,data:gwnHp3TqW8Rgs0YiA/GCu0K3ayrnook79wJNTg==,iv:TYh+2CSjDxlbI4OJUCN/qW5ItAFB22M/noTFq/XR3gs=,tag:q5LhYenG9uGOBQRnUVOV9Q==,type:str]
    APP_DATABASE__PASSWORD: ENC[AES256_GCM,data:PeRTw4/w6LeYyZBTaY7CPsYPN6LyK7UeLrvDL8YKxwK8+bZDQN8P82uuSpg=,iv:ap7ygprX1TChgHQx3e4btr4mFctXMBbmU4h+JXb4cUc=,tag:35+jkXJbl4fR/HTbJXgX0w==,type:str]
    #ENC[AES256_GCM,data:tYBkcaBmVWqMIQ==,iv:4H8sh86L/INYyesvdiz7++B24DS0zPkVtmpr/Xz7eyU=,tag:jsafePT2UiqR8x+XEYkNOw==,type:comment]
    APP_AUTH__BACKEND_CLIENT_SECRET: ENC[AES256_GCM,data:JxWacNIZD1x1fEFij4+rcJ9JA8Acv3GhKCgj6n9sA7eKymwSKPkGUFcCcRo=,iv:Mb6SP77QlF7n/iAR7ae+17AdHRJ7hGgQ8GUGoE4ddc8=,tag:6pooZPa1iy4hshN8ESaHtQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T16:17:38Z"
    mac: ENC[AES256_GCM,data:cn4cGpVJ++56FSTnZViybF29hGA1mmDGkdZB/3CDK4a8ZaEFD+8Ho1OCYwLwU5xPCp30lb6Vn8cn4FGqq6Y19teZeF2t3y/1l65r/fOUGGDxsjDi6no9DtgZGxK1l+C9TXQH6jaGnUOpaYlwpzHQTh68CSnjx69eAUfELFK6oSc=,iv:0u+7RlqzV5kqV00+SSrZBol9FPesNRSFvHe0we9+fcU=,tag:SZYktSUg2pzND9EJqdjVqQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
