apiVersion: batch/v1
kind: CronJob
metadata:
  name: clean-db
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: init-migrations
              image: green-ecolution-image
              imagePullPolicy: Always
              command: ["./migrate"]
              args: ["reset", "--with-seed"]
              envFrom:
                - configMapRef:
                    name: backend-config
                - secretRef:
                    name: backend-secrets
          restartPolicy: OnFailure
