apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- cron-job.yaml
- ../base/green-ecolution
images:
- name: green-ecolution-image
  newName: ghcr.io/green-ecolution/green-ecolution
  newTag: v0.2.1
generators:
- ./secret-generator.yaml
patches:
- path: config.yaml
- path: green-ecolution-deployment.yaml
