#ENC[AES256_GCM,data:CE0IV5i6nmUWj0UP3zaqdd37CwxCfF2VDFA4N8oH9cjXMmloOleSxVaYz/yGKORt8zzhdblnxYyvjQ==,iv:tLJk/59M1CeOz2Mo8HjD7Je/D++ulOABkbmwi0+WCwI=,tag:TwBNVbJs2I31aXyo91K7uw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    APP_DATABASE__USERNAME: ENC[AES256_GCM,data:D+StPLFVXW0O3uYMNO/WcSixgXzoCoeIpXeV6g==,iv:M5juoNIFNGlU+2e3vklGvt46vvS920QL6QVA8EUpQGc=,tag:liAJ3TSARbsrczh+SginHw==,type:str]
    APP_DATABASE__PASSWORD: ENC[AES256_GCM,data:BWfoZRS2XEeD4nu63bU+iMFVmN/ZLx8knQsvlcVCtO7IE194u7nTQPsuzjEhUEgyMgUp2Rjrhf/h08yopJrUyg==,iv:wis5GMkELT1CfhN+dcl1oKc1fV2No8CUJ1r8kKsTJtg=,tag:QhLqzwGhFPfggAVEeTlWsg==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMWF4QVJpQ0lpVUpxRmpL
            bm03TDJlOGIwM25kZnRLclhkb0piTWZWb0RBCmxNejdYTnRlaDVqdFVsai8zZllT
            MnhLV3BseFJCSmNDSjg1VmdQT0NRV00KLS0tIExmVjNwQnNBWTYxSGY5VkxJa1dO
            bTdyYllrNTNZTjl2QlVpc2N1eGNmc2cK9GxRJB+6tqKMpHFtBp8J/OHU5d2haFEg
            El1LAeEtbB28LRj6Ia3E4gv9hyj0LGzBaz0Rizi9AEtUZgQDjuWF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T16:19:21Z"
    mac: ENC[AES256_GCM,data:6XONyIPgbGvFs8a6hRhyAdt5u2FIpNC3CuI7CFqe4Zw2cDMYaB/EtqNvx/2kBVr78+HdF65lFjLvdS/69CbqUn5Z7qgIU1ZM+OqzCZgI4Om6C2LetOhKhtWGhcdJ361E0vL9xD5R0TK+AxugcPEhAzNMTTfGE6f0mkwKhXVCOa8=,iv:OATb8uo30om0ZDqyEZwJmBI4gnKug/qsGLxk9CMmT/Q=,tag:fECOWKgCj1Vtkyk8ZhoWTQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
