with-expecter: true
packages:
  github.com/green-ecolution/green-ecolution/backend/internal/application/ports:
    config: 
      dir: ./internal/application/_mock
    interfaces:
      InfoService:
      MqttService:
      TreeService:
      TreeClusterService:
      GeoClusterLocator:
      AuthService:
      RegionService:
      SensorService:
      VehicleService:
      PluginService:
      WateringPlanService:
      EvaluationService:
      Service:
      ServicesInterface:
  github.com/green-ecolution/green-ecolution/backend/internal/domain/shared:
    config: 
      dir: ./internal/infrastructure/_mock
    interfaces:
      InfoRepository:
      SensorRepository:
      TreeRepository:
      TreeClusterRepository:
      AuthRepository:
      UserRepository:
      RegionRepository:
      ImageRepository:
      VehicleRepository:
      WateringPlanRepository:
      RoutingRepository:
      S3Repository:
  github.com/green-ecolution/green-ecolution/backend/internal/infrastructure/postgres/_sqlc:
    config: 
      dir: ./internal/infrastructure/_mock
      outpkg: shared
    interfaces:
      Querier:
