# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  template:
    spec:
      initContainers:
        - name: init-migrations
          image: backend-image
          imagePullPolicy: Always
          command: ["./migrate"]
          args: ["reset", "--with-seed"]
          env:
            - name: APP_DATABASE__DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: GE_SERVER_DATABASE_NAME
            - name: APP_DATABASE__HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: GE_SERVER_DATABASE_HOST
            - name: APP_DATABASE__PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: GE_SERVER_DATABASE_PORT
            - name: APP_DATABASE__USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GE_SERVER_DATABASE_USERNAME
            - name: APP_DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GE_SERVER_DATABASE_PASSWORD
