# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENVIRONMENT: "staging"
  APP_APPLICATION__PORT: "3000"
  APP_APPLICATION__BASE_URL: "https://app.stage.green-ecolution.de"

  APP_DATABASE__HOST: "postgresql.postgres.svc.cluster.local"
  APP_DATABASE__PORT: "5432"
  APP_DATABASE__DATABASE_NAME: "green-ecolution-stage"
  APP_DATABASE__REQUIRE_SSL: "false"

  APP_AUTH__ENABLED: "true"
  APP_AUTH__ISSUER_URL: "https://auth.green-ecolution.de/realms/green-ecolution-stage"
  APP_AUTH__FRONTEND_CLIENT_ID: "frontend"
  APP_AUTH__BACKEND_CLIENT_ID: "backend"
  APP_AUTH__DEFAULT_REDIRECT_URL: "https://app.stage.green-ecolution.de"

  APP_MQTT__ENABLED: "true"
  APP_MQTT__BROKER_URL: "mqtt://eu1.cloud.thethings.industries:1883"
  APP_MQTT__TOPIC: "v3/bodenfeuchtetbz@smarte-grenzregion-lns/devices/+/up"

  TZ: "Europe/Berlin"
