#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    APP_MQTT__CLIENT_ID: ENC[AES256_GCM,data:j4mJ8HxhBHV2dTSmtdVURVXxM90=,iv:LFRe7GmxMjOOc2vgpBQXJzCNOWUECJmUeYFrQSX0ywM=,tag:HeHPj/FfOYvMBOn6qWMldQ==,type:str]
    APP_MQTT__USERNAME: ENC[AES256_GCM,data:FAzTn3ZYyXXBBJaYVrLaLA+f+3/2SMq/jRuql9Zo40mGZ21oyJaqgl5dPQXS6XOIVYLoyw==,iv:p4xr2y9UuRY1hJkvIo75v3D+rQ2BwRiozRLAMTzbW0U=,tag:UYqS2jdFQ+05UckpQcK9Kg==,type:str]
    APP_MQTT__PASSWORD: ENC[AES256_GCM,data:3AnWU5bq9pGSGrzaZW1XYinVbMI7JL5rmdjmMb02WN9gn62TSBPnQyTjay5oR1igHdkqASe3qNEDsgj95evah4QamDdvyax6gP5rckAiOrgjfu8RDDM8lawiE0WfHLI1mOl4e6OLQCqGVeAwjI/dZW7x6f2Iizc0AgTZNcMOKIhHMH7n,iv:0MHlznaMszH5lRRfG/XBqtKXf41j+QUiWWJFIHZ9X7A=,tag:cMhpToTRueE/UJGptTOdgA==,type:str]
    APP_DATABASE__USERNAME: ENC[AES256_GCM,data:nDDdtwNlobEWra+6HqUOSrbioWaZobmmykRY+g==,iv:orOeso6CcIhkh8ay4VM9+uk7m+PBqqd9slphhote8kI=,tag:hcMYHPm99FiW3QI3GBN6fg==,type:str]
    APP_DATABASE__PASSWORD: ENC[AES256_GCM,data:X0UhXOIGsZe2v67sX9GvRGatM9Gqg2Q+tS5LxLuh7PWpfrvwA3s2/A==,iv:8HREp82mglsbnitWq02LeLy+zD9kWFFYLJn+WL1ErjQ=,tag:d9hHWty0usVNIEH/aO/i0Q==,type:str]
    APP_AUTH__BACKEND_CLIENT_SECRET: ENC[AES256_GCM,data:3IDUHpcfGqYgNnOiGRq90CnSg9PrTJm+daTSaVMZ6JScZ3hSXGD/+eCTdZo=,iv:PmMWKD9s0qMaO+e/j00HBOKV6Qpu03lrTc02z1D7LpQ=,tag:noXd50zCEhU1bCGNHxl70w==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T09:59:14Z"
    mac: ENC[AES256_GCM,data:WuyNvpMurgo1S4PghUIdXqWdQI28dCdet5J+3riwQG9H+FfokTTl4z0TVwoSiHaYp4f3w2PruFNcx0hT8rqoDrRkEi//b96NLBJVxjBMXS5a6W3RDfu74UR8zlw+j2MqzM7UsVtEbV/KygSYZ43hggkmphOZjj5O2MjsbZVvODA=,iv:W01IZw6KfvFaSwbrZrqXBjUpnD9dy4a3AsJHVLAcXTs=,tag:e+PbzIUIOStsCXeU6VDbEQ==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
