#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    APP_MQTT__CLIENT_ID: ENC[AES256_GCM,data:o2ljEN5C7RZMYao+Ycp1,iv:pT/M8OL/5l95yWK5kIE/PGC8kiQqiux5NFR1c3PwqhI=,tag:goHjapdNaIndh/YqYfvqwg==,type:str]
    APP_MQTT__USERNAME: ENC[AES256_GCM,data:iY4kzpaC7tmA7BNM6SJrXc8DTSmE3vSGy7iisaOnrClA+S4jSuU=,iv:ALCbO+3Ah1W9v33CxdmSk9Ybmh302OmYg4ALB+O0IXA=,tag:aHX3qjm1SIGAhLkSwmERDw==,type:str]
    APP_MQTT__PASSWORD: ENC[AES256_GCM,data:5aKeYIQf/G6wmmwh1iJYlbbuljKELCpsM8vv3Vc9OHHdaBJRLwfkY28Nmue41wb7pYoYQ40B/z6XtA5Eigym3t+NMhL1qtFHzrahaleRwum6hPyhzz+4fU/dk7lGICwL+mk=,iv:3bfdaJA96NX2Z4UuO10ncTjr9ZN6hRwjWY36ileEwyU=,tag:SwEaY3HdBNraTs2X36sBMg==,type:str]
    APP_DATABASE__USERNAME: ENC[AES256_GCM,data:O9zLg7TCMC/7tsFe0+um9VwHsFbW,iv:0jfJwngDW7rSDAWftGarKzllesy+RGGTl+fvC10kxMo=,tag:9lCjUHXMbbZlWp6ry4HNjQ==,type:str]
    APP_DATABASE__PASSWORD: ENC[AES256_GCM,data:GAYK3CJMD/UgHT+Kw60PWwC9faTk905CDJnaunVG,iv:E2UUdS50UrBNpwvQYuhkm/efQep4m0m0sBQPTXXU5vg=,tag:nroEDltmktjqRWg/upSx7w==,type:str]
    APP_AUTH__BACKEND_CLIENT_SECRET: ENC[AES256_GCM,data:z8HdCAlYE9BO4CP7hdiemrsbVWlDLEZSLpJHknZZqwE=,iv:quDU4khqxUYePaBKP1CrC3N+gGV+8Jvgr6un17shzf4=,tag:RsMFTqqUmhHq4i+0Ti2jPw==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T06:46:57Z"
    mac: ENC[AES256_GCM,data:Y697N2qin3CmGhDj3PNlSPhutfWZ10egZo8soM+1mJCVPbZO/94r3vqNIi8qu4LZcMjPRKlxCZu0jZIjlbDXf4WEQdXRvstqmb53PTAFtE+1ro/io2l934cL5b+5IANNf6Nkcgmb+KBxbJ2Cs9BzO825LlQxbYnHBzIIyBLhvLk=,iv:hvw+SwKVLnovUIlXiFokP107NRoRRMwHX1aHcJgF2SI=,tag:bX8RYWWDgZevw83TxWMADA==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
