#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    APP_MQTT__CLIENT_ID: ENC[AES256_GCM,data:VfnNFr2xB4EiEZm06hNtVA==,iv:fNLhsMUx/QLhoV4s4C2RD9lYfdUNa7/ZKYkRXz8HEAg=,tag:ppagn1fxYoSiRFmvfuxyyg==,type:str]
    APP_MQTT__USERNAME: ENC[AES256_GCM,data:hyABsZ12AV80bqwWYRQ428kNKC+L8N2e,iv:5AaISgHPDqwIM2cW5cq25i636FHJ3IVpIrr28GGf378=,tag:PW65EofDr9QVXtYqs+I1KA==,type:str]
    APP_MQTT__PASSWORD: ENC[AES256_GCM,data:DBKAaThHXJDOKNY8VVWnT/K9jGAQt3coRP14Gw/+PSGxBBsNczwLQ6OsOx69G29dPeum4W0C+9uZRAxvC0SkvD2y/sYf6wxgLde3tFjlNHDQ6nVFxL0pULxw1mrN1gBOY72ay2NV3jZXJqd2LKKYmAAWNIZN4zMghO4u/RidXmXYiods,iv:4Zew9St8BmK9MNG3zeOJ8Q0GU/FvHLRsFkdpYVND75E=,tag:OlJX3IWmpZRSSoBBLyKGSA==,type:str]
    APP_DATABASE__USERNAME: ENC[AES256_GCM,data:eSQG0c/Mgc0L9DZhcoWGXAqnRml5nCyK9upmYw==,iv:MLKkuWThQ3df7rrbWMm721ZZbOIj7NqAdVTWYuve5Rw=,tag:ZcKlvm3T2QVG0VcLtcF1bQ==,type:str]
    APP_DATABASE__PASSWORD: ENC[AES256_GCM,data:0aMcOLwAI4vtVvjGtc34n99E7WYuwrwvNxRJzzY/cUVhDp5ihWLPdg==,iv:rPam+eJBc3UWxZivABa8Bqa0TV0XVz4WJay2EZJXvXo=,tag:oKS3jKAZWtAfvTwlqukWIg==,type:str]
    APP_AUTH__BACKEND_CLIENT_SECRET: ENC[AES256_GCM,data:xLBNvPQ4EUIoExdW8eNTaJtxHLUHUZ6Av2aLUueBK8w/gZwbasU6C6iqftU=,iv:hqaJSgDDb9Meqfpqo7AxCI8ko/JfODUuNwn1aawtM/I=,tag:+E4Iya/9aI03XQfLH0VNTQ==,type:str]
sops:
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T16:16:26Z"
    mac: ENC[AES256_GCM,data:hFveeyVryGcqJoTTAojqlS6vbieqAuoihVNfTaTIRo98wfhciec8+H/7PQa1zIeN+f7eYb4WcGNjs0/b9hKYoYuJQ/IRJsCWlm63JJdOpyaBMRrWKNubLkM43prvqpQ6derCIymX8hAH/KewZLVYDLlsGyVL/R2Caq7sClSYV8U=,iv:s0kx3/7dpKEy4n7PeZrmwyQDYDHV1g3s/pQR7PdJpWY=,tag:5iZTKpW9xhX2hESI2Aha7Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.12.1
