/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v1.2.0-37-g1c5af7f8-stage
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Pagination
 */
export interface Pagination {
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    nextPage: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    prevPage: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    totalPages: number;
    /**
     * 
     * @type {number}
     * @memberof Pagination
     */
    totalRecords: number;
}

/**
 * Check if a given object implements the Pagination interface.
 */
export function instanceOfPagination(value: object): value is Pagination {
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('nextPage' in value) || value['nextPage'] === undefined) return false;
    if (!('prevPage' in value) || value['prevPage'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('totalRecords' in value) || value['totalRecords'] === undefined) return false;
    return true;
}

export function PaginationFromJSON(json: any): Pagination {
    return PaginationFromJSONTyped(json, false);
}

export function PaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pagination {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'],
        'nextPage': json['next_page'],
        'prevPage': json['prev_page'],
        'totalPages': json['total_pages'],
        'totalRecords': json['total_records'],
    };
}

export function PaginationToJSON(json: any): Pagination {
    return PaginationToJSONTyped(json, false);
}

export function PaginationToJSONTyped(value?: Pagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'next_page': value['nextPage'],
        'prev_page': value['prevPage'],
        'total_pages': value['totalPages'],
        'total_records': value['totalRecords'],
    };
}

