/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v1.2.0-37-g1c5af7f8-stage
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegionEvaluation
 */
export interface RegionEvaluation {
    /**
     * 
     * @type {string}
     * @memberof RegionEvaluation
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof RegionEvaluation
     */
    wateringPlanCount: number;
}

/**
 * Check if a given object implements the RegionEvaluation interface.
 */
export function instanceOfRegionEvaluation(value: object): value is RegionEvaluation {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('wateringPlanCount' in value) || value['wateringPlanCount'] === undefined) return false;
    return true;
}

export function RegionEvaluationFromJSON(json: any): RegionEvaluation {
    return RegionEvaluationFromJSONTyped(json, false);
}

export function RegionEvaluationFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegionEvaluation {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'wateringPlanCount': json['watering_plan_count'],
    };
}

export function RegionEvaluationToJSON(json: any): RegionEvaluation {
    return RegionEvaluationToJSONTyped(json, false);
}

export function RegionEvaluationToJSONTyped(value?: RegionEvaluation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'watering_plan_count': value['wateringPlanCount'],
    };
}

