/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v1.2.0-37-g1c5af7f8-stage
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleType } from './VehicleType';
import {
    VehicleTypeFromJSON,
    VehicleTypeFromJSONTyped,
    VehicleTypeToJSON,
    VehicleTypeToJSONTyped,
} from './VehicleType';
import type { DrivingLicense } from './DrivingLicense';
import {
    DrivingLicenseFromJSON,
    DrivingLicenseFromJSONTyped,
    DrivingLicenseToJSON,
    DrivingLicenseToJSONTyped,
} from './DrivingLicense';
import type { VehicleStatus } from './VehicleStatus';
import {
    VehicleStatusFromJSON,
    VehicleStatusFromJSONTyped,
    VehicleStatusToJSON,
    VehicleStatusToJSONTyped,
} from './VehicleStatus';

/**
 * 
 * @export
 * @interface VehicleCreate
 */
export interface VehicleCreate {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof VehicleCreate
     */
    additionalInformation?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof VehicleCreate
     */
    description: string;
    /**
     * 
     * @type {DrivingLicense}
     * @memberof VehicleCreate
     */
    drivingLicense: DrivingLicense;
    /**
     * 
     * @type {number}
     * @memberof VehicleCreate
     */
    height: number;
    /**
     * 
     * @type {number}
     * @memberof VehicleCreate
     */
    length: number;
    /**
     * 
     * @type {string}
     * @memberof VehicleCreate
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleCreate
     */
    numberPlate: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleCreate
     */
    provider?: string;
    /**
     * 
     * @type {VehicleStatus}
     * @memberof VehicleCreate
     */
    status: VehicleStatus;
    /**
     * 
     * @type {VehicleType}
     * @memberof VehicleCreate
     */
    type: VehicleType;
    /**
     * 
     * @type {number}
     * @memberof VehicleCreate
     */
    waterCapacity: number;
    /**
     * 
     * @type {number}
     * @memberof VehicleCreate
     */
    weight: number;
    /**
     * 
     * @type {number}
     * @memberof VehicleCreate
     */
    width: number;
}



/**
 * Check if a given object implements the VehicleCreate interface.
 */
export function instanceOfVehicleCreate(value: object): value is VehicleCreate {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('drivingLicense' in value) || value['drivingLicense'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('numberPlate' in value) || value['numberPlate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('waterCapacity' in value) || value['waterCapacity'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    return true;
}

export function VehicleCreateFromJSON(json: any): VehicleCreate {
    return VehicleCreateFromJSONTyped(json, false);
}

export function VehicleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalInformation': json['additional_information'] == null ? undefined : json['additional_information'],
        'description': json['description'],
        'drivingLicense': DrivingLicenseFromJSON(json['driving_license']),
        'height': json['height'],
        'length': json['length'],
        'model': json['model'],
        'numberPlate': json['number_plate'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'status': VehicleStatusFromJSON(json['status']),
        'type': VehicleTypeFromJSON(json['type']),
        'waterCapacity': json['water_capacity'],
        'weight': json['weight'],
        'width': json['width'],
    };
}

export function VehicleCreateToJSON(json: any): VehicleCreate {
    return VehicleCreateToJSONTyped(json, false);
}

export function VehicleCreateToJSONTyped(value?: VehicleCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'additional_information': value['additionalInformation'],
        'description': value['description'],
        'driving_license': DrivingLicenseToJSON(value['drivingLicense']),
        'height': value['height'],
        'length': value['length'],
        'model': value['model'],
        'number_plate': value['numberPlate'],
        'provider': value['provider'],
        'status': VehicleStatusToJSON(value['status']),
        'type': VehicleTypeToJSON(value['type']),
        'water_capacity': value['waterCapacity'],
        'weight': value['weight'],
        'width': value['width'],
    };
}

