name: Bug Report
description: Report a bug
labels: ["type: bug", "priority: high"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      value: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria (Definition of Done)
      value: |
        - [ ] Bug is fixed
        - [ ] Regression test added
        - [ ] No new errors in logs
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v0.1.0
