// Code generated by mockery v2.52.2. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockServicesInterface is an autogenerated mock type for the ServicesInterface type
type MockServicesInterface struct {
	mock.Mock
}

type MockServicesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServicesInterface) EXPECT() *MockServicesInterface_Expecter {
	return &MockServicesInterface_Expecter{mock: &_m.Mock}
}

// AllServicesReady provides a mock function with no fields
func (_m *MockServicesInterface) AllServicesReady() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AllServicesReady")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockServicesInterface_AllServicesReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllServicesReady'
type MockServicesInterface_AllServicesReady_Call struct {
	*mock.Call
}

// AllServicesReady is a helper method to define mock.On call
func (_e *MockServicesInterface_Expecter) AllServicesReady() *MockServicesInterface_AllServicesReady_Call {
	return &MockServicesInterface_AllServicesReady_Call{Call: _e.mock.On("AllServicesReady")}
}

func (_c *MockServicesInterface_AllServicesReady_Call) Run(run func()) *MockServicesInterface_AllServicesReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServicesInterface_AllServicesReady_Call) Return(_a0 bool) *MockServicesInterface_AllServicesReady_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServicesInterface_AllServicesReady_Call) RunAndReturn(run func() bool) *MockServicesInterface_AllServicesReady_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServicesInterface creates a new instance of MockServicesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServicesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServicesInterface {
	mock := &MockServicesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
