// Code generated by mockery v2.52.2. DO NOT EDIT.

package service

import (
	context "context"

	entities "github.com/green-ecolution/backend/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockInfoService is an autogenerated mock type for the InfoService type
type MockInfoService struct {
	mock.Mock
}

type MockInfoService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInfoService) EXPECT() *MockInfoService_Expecter {
	return &MockInfoService_Expecter{mock: &_m.Mock}
}

// GetAppInfo provides a mock function with given fields: _a0
func (_m *MockInfoService) GetAppInfo(_a0 context.Context) (*entities.App, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAppInfo")
	}

	var r0 *entities.App
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.App, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.App); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.App)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInfoService_GetAppInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppInfo'
type MockInfoService_GetAppInfo_Call struct {
	*mock.Call
}

// GetAppInfo is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockInfoService_Expecter) GetAppInfo(_a0 interface{}) *MockInfoService_GetAppInfo_Call {
	return &MockInfoService_GetAppInfo_Call{Call: _e.mock.On("GetAppInfo", _a0)}
}

func (_c *MockInfoService_GetAppInfo_Call) Run(run func(_a0 context.Context)) *MockInfoService_GetAppInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInfoService_GetAppInfo_Call) Return(_a0 *entities.App, _a1 error) *MockInfoService_GetAppInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInfoService_GetAppInfo_Call) RunAndReturn(run func(context.Context) (*entities.App, error)) *MockInfoService_GetAppInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppInfoResponse provides a mock function with given fields: _a0
func (_m *MockInfoService) GetAppInfoResponse(_a0 context.Context) (*entities.App, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAppInfoResponse")
	}

	var r0 *entities.App
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.App, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.App); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.App)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInfoService_GetAppInfoResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppInfoResponse'
type MockInfoService_GetAppInfoResponse_Call struct {
	*mock.Call
}

// GetAppInfoResponse is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockInfoService_Expecter) GetAppInfoResponse(_a0 interface{}) *MockInfoService_GetAppInfoResponse_Call {
	return &MockInfoService_GetAppInfoResponse_Call{Call: _e.mock.On("GetAppInfoResponse", _a0)}
}

func (_c *MockInfoService_GetAppInfoResponse_Call) Run(run func(_a0 context.Context)) *MockInfoService_GetAppInfoResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInfoService_GetAppInfoResponse_Call) Return(_a0 *entities.App, _a1 error) *MockInfoService_GetAppInfoResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInfoService_GetAppInfoResponse_Call) RunAndReturn(run func(context.Context) (*entities.App, error)) *MockInfoService_GetAppInfoResponse_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with no fields
func (_m *MockInfoService) Ready() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockInfoService_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockInfoService_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *MockInfoService_Expecter) Ready() *MockInfoService_Ready_Call {
	return &MockInfoService_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *MockInfoService_Ready_Call) Run(run func()) *MockInfoService_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInfoService_Ready_Call) Return(_a0 bool) *MockInfoService_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInfoService_Ready_Call) RunAndReturn(run func() bool) *MockInfoService_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInfoService creates a new instance of MockInfoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInfoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInfoService {
	mock := &MockInfoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
