application:
  port: 3020
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "postgres"
  max_connections: 5
  log_statements_level: "debug"
  slow_query_threshold_ms: 500
log:
  level: "info,sqlx=warn,tower_http=debug"
  format: "pretty"
cors:
  allowed_origins:
    - "*"
auth:
  enabled: true
  jwks_refresh_interval_secs: 3600
  jwks_refresh_timeout_secs: 5
mqtt:
  enabled: false
  broker_url: ""
  topic: ""
  client_id: "green-ecolution"
  keep_alive_secs: 30
map:
  center: [54.792277136221905, 9.43580607453268]
  bbox: [54.714822, 9.285796, 54.860127, 9.583800]
info:
  update_check_repo: "green-ecolution/green-ecolution"
  repository_url: "https://github.com/green-ecolution/"
routing:
  enabled: false
plugins:
  enabled: false
