// Code generated by mockery v2.52.2. DO NOT EDIT.

package storage

import (
	context "context"

	entities "github.com/green-ecolution/green-ecolution/backend/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockInfoRepository is an autogenerated mock type for the InfoRepository type
type MockInfoRepository struct {
	mock.Mock
}

type MockInfoRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInfoRepository) EXPECT() *MockInfoRepository_Expecter {
	return &MockInfoRepository_Expecter{mock: &_m.Mock}
}

// GetAppInfo provides a mock function with given fields: ctx
func (_m *MockInfoRepository) GetAppInfo(ctx context.Context) (*entities.App, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAppInfo")
	}

	var r0 *entities.App
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.App, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.App); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.App)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInfoRepository_GetAppInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppInfo'
type MockInfoRepository_GetAppInfo_Call struct {
	*mock.Call
}

// GetAppInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInfoRepository_Expecter) GetAppInfo(ctx interface{}) *MockInfoRepository_GetAppInfo_Call {
	return &MockInfoRepository_GetAppInfo_Call{Call: _e.mock.On("GetAppInfo", ctx)}
}

func (_c *MockInfoRepository_GetAppInfo_Call) Run(run func(ctx context.Context)) *MockInfoRepository_GetAppInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInfoRepository_GetAppInfo_Call) Return(_a0 *entities.App, _a1 error) *MockInfoRepository_GetAppInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInfoRepository_GetAppInfo_Call) RunAndReturn(run func(context.Context) (*entities.App, error)) *MockInfoRepository_GetAppInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetMapInfo provides a mock function with given fields: ctx
func (_m *MockInfoRepository) GetMapInfo(ctx context.Context) (*entities.Map, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMapInfo")
	}

	var r0 *entities.Map
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.Map, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.Map); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Map)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInfoRepository_GetMapInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMapInfo'
type MockInfoRepository_GetMapInfo_Call struct {
	*mock.Call
}

// GetMapInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInfoRepository_Expecter) GetMapInfo(ctx interface{}) *MockInfoRepository_GetMapInfo_Call {
	return &MockInfoRepository_GetMapInfo_Call{Call: _e.mock.On("GetMapInfo", ctx)}
}

func (_c *MockInfoRepository_GetMapInfo_Call) Run(run func(ctx context.Context)) *MockInfoRepository_GetMapInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInfoRepository_GetMapInfo_Call) Return(_a0 *entities.Map, _a1 error) *MockInfoRepository_GetMapInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInfoRepository_GetMapInfo_Call) RunAndReturn(run func(context.Context) (*entities.Map, error)) *MockInfoRepository_GetMapInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetServerInfo provides a mock function with given fields: ctx
func (_m *MockInfoRepository) GetServerInfo(ctx context.Context) (*entities.Server, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetServerInfo")
	}

	var r0 *entities.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.Server, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.Server); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInfoRepository_GetServerInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerInfo'
type MockInfoRepository_GetServerInfo_Call struct {
	*mock.Call
}

// GetServerInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInfoRepository_Expecter) GetServerInfo(ctx interface{}) *MockInfoRepository_GetServerInfo_Call {
	return &MockInfoRepository_GetServerInfo_Call{Call: _e.mock.On("GetServerInfo", ctx)}
}

func (_c *MockInfoRepository_GetServerInfo_Call) Run(run func(ctx context.Context)) *MockInfoRepository_GetServerInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInfoRepository_GetServerInfo_Call) Return(_a0 *entities.Server, _a1 error) *MockInfoRepository_GetServerInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInfoRepository_GetServerInfo_Call) RunAndReturn(run func(context.Context) (*entities.Server, error)) *MockInfoRepository_GetServerInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetServices provides a mock function with given fields: ctx
func (_m *MockInfoRepository) GetServices(ctx context.Context) (*entities.Services, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetServices")
	}

	var r0 *entities.Services
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.Services, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.Services); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Services)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInfoRepository_GetServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServices'
type MockInfoRepository_GetServices_Call struct {
	*mock.Call
}

// GetServices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInfoRepository_Expecter) GetServices(ctx interface{}) *MockInfoRepository_GetServices_Call {
	return &MockInfoRepository_GetServices_Call{Call: _e.mock.On("GetServices", ctx)}
}

func (_c *MockInfoRepository_GetServices_Call) Run(run func(ctx context.Context)) *MockInfoRepository_GetServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInfoRepository_GetServices_Call) Return(_a0 *entities.Services, _a1 error) *MockInfoRepository_GetServices_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInfoRepository_GetServices_Call) RunAndReturn(run func(context.Context) (*entities.Services, error)) *MockInfoRepository_GetServices_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatistics provides a mock function with given fields: ctx
func (_m *MockInfoRepository) GetStatistics(ctx context.Context) (*entities.DataStatistics, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatistics")
	}

	var r0 *entities.DataStatistics
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entities.DataStatistics, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entities.DataStatistics); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.DataStatistics)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInfoRepository_GetStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistics'
type MockInfoRepository_GetStatistics_Call struct {
	*mock.Call
}

// GetStatistics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInfoRepository_Expecter) GetStatistics(ctx interface{}) *MockInfoRepository_GetStatistics_Call {
	return &MockInfoRepository_GetStatistics_Call{Call: _e.mock.On("GetStatistics", ctx)}
}

func (_c *MockInfoRepository_GetStatistics_Call) Run(run func(ctx context.Context)) *MockInfoRepository_GetStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInfoRepository_GetStatistics_Call) Return(_a0 *entities.DataStatistics, _a1 error) *MockInfoRepository_GetStatistics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInfoRepository_GetStatistics_Call) RunAndReturn(run func(context.Context) (*entities.DataStatistics, error)) *MockInfoRepository_GetStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInfoRepository creates a new instance of MockInfoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInfoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInfoRepository {
	mock := &MockInfoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
