// Code generated by mockery v2.52.2. DO NOT EDIT.

package storage

import (
	context "context"

	entities "github.com/green-ecolution/green-ecolution/backend/internal/entities"
	mock "github.com/stretchr/testify/mock"

	storage "github.com/green-ecolution/green-ecolution/backend/internal/storage"

	uuid "github.com/google/uuid"
)

// MockWateringPlanRepository is an autogenerated mock type for the WateringPlanRepository type
type MockWateringPlanRepository struct {
	mock.Mock
}

type MockWateringPlanRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWateringPlanRepository) EXPECT() *MockWateringPlanRepository_Expecter {
	return &MockWateringPlanRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, fn
func (_m *MockWateringPlanRepository) Create(ctx context.Context, fn func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)) (*entities.WateringPlan, error) {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.WateringPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)) (*entities.WateringPlan, error)); ok {
		return rf(ctx, fn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)) *entities.WateringPlan); ok {
		r0 = rf(ctx, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)) error); ok {
		r1 = rf(ctx, fn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWateringPlanRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(*entities.WateringPlan , storage.WateringPlanRepository)(bool , error)
func (_e *MockWateringPlanRepository_Expecter) Create(ctx interface{}, fn interface{}) *MockWateringPlanRepository_Create_Call {
	return &MockWateringPlanRepository_Create_Call{Call: _e.mock.On("Create", ctx, fn)}
}

func (_c *MockWateringPlanRepository_Create_Call) Run(run func(ctx context.Context, fn func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error))) *MockWateringPlanRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)))
	})
	return _c
}

func (_c *MockWateringPlanRepository_Create_Call) Return(_a0 *entities.WateringPlan, _a1 error) *MockWateringPlanRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_Create_Call) RunAndReturn(run func(context.Context, func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)) (*entities.WateringPlan, error)) *MockWateringPlanRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockWateringPlanRepository) Delete(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWateringPlanRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWateringPlanRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWateringPlanRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockWateringPlanRepository_Delete_Call {
	return &MockWateringPlanRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockWateringPlanRepository_Delete_Call) Run(run func(ctx context.Context, id int32)) *MockWateringPlanRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWateringPlanRepository_Delete_Call) Return(_a0 error) *MockWateringPlanRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWateringPlanRepository_Delete_Call) RunAndReturn(run func(context.Context, int32) error) *MockWateringPlanRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, query
func (_m *MockWateringPlanRepository) GetAll(ctx context.Context, query entities.Query) ([]*entities.WateringPlan, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entities.WateringPlan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Query) ([]*entities.WateringPlan, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Query) []*entities.WateringPlan); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Query) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.Query) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWateringPlanRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockWateringPlanRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - query entities.Query
func (_e *MockWateringPlanRepository_Expecter) GetAll(ctx interface{}, query interface{}) *MockWateringPlanRepository_GetAll_Call {
	return &MockWateringPlanRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, query)}
}

func (_c *MockWateringPlanRepository_GetAll_Call) Run(run func(ctx context.Context, query entities.Query)) *MockWateringPlanRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Query))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetAll_Call) Return(_a0 []*entities.WateringPlan, _a1 int64, _a2 error) *MockWateringPlanRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockWateringPlanRepository_GetAll_Call) RunAndReturn(run func(context.Context, entities.Query) ([]*entities.WateringPlan, int64, error)) *MockWateringPlanRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUserCount provides a mock function with given fields: ctx
func (_m *MockWateringPlanRepository) GetAllUserCount(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUserCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetAllUserCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUserCount'
type MockWateringPlanRepository_GetAllUserCount_Call struct {
	*mock.Call
}

// GetAllUserCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWateringPlanRepository_Expecter) GetAllUserCount(ctx interface{}) *MockWateringPlanRepository_GetAllUserCount_Call {
	return &MockWateringPlanRepository_GetAllUserCount_Call{Call: _e.mock.On("GetAllUserCount", ctx)}
}

func (_c *MockWateringPlanRepository_GetAllUserCount_Call) Run(run func(ctx context.Context)) *MockWateringPlanRepository_GetAllUserCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetAllUserCount_Call) Return(_a0 int64, _a1 error) *MockWateringPlanRepository_GetAllUserCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetAllUserCount_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockWateringPlanRepository_GetAllUserCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockWateringPlanRepository) GetByID(ctx context.Context, id int32) (*entities.WateringPlan, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.WateringPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*entities.WateringPlan, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *entities.WateringPlan); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWateringPlanRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWateringPlanRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockWateringPlanRepository_GetByID_Call {
	return &MockWateringPlanRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockWateringPlanRepository_GetByID_Call) Run(run func(ctx context.Context, id int32)) *MockWateringPlanRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetByID_Call) Return(_a0 *entities.WateringPlan, _a1 error) *MockWateringPlanRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetByID_Call) RunAndReturn(run func(context.Context, int32) (*entities.WateringPlan, error)) *MockWateringPlanRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCount provides a mock function with given fields: ctx, query
func (_m *MockWateringPlanRepository) GetCount(ctx context.Context, query entities.Query) (int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Query) (int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Query) int64); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Query) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCount'
type MockWateringPlanRepository_GetCount_Call struct {
	*mock.Call
}

// GetCount is a helper method to define mock.On call
//   - ctx context.Context
//   - query entities.Query
func (_e *MockWateringPlanRepository_Expecter) GetCount(ctx interface{}, query interface{}) *MockWateringPlanRepository_GetCount_Call {
	return &MockWateringPlanRepository_GetCount_Call{Call: _e.mock.On("GetCount", ctx, query)}
}

func (_c *MockWateringPlanRepository_GetCount_Call) Run(run func(ctx context.Context, query entities.Query)) *MockWateringPlanRepository_GetCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Query))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetCount_Call) Return(_a0 int64, _a1 error) *MockWateringPlanRepository_GetCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetCount_Call) RunAndReturn(run func(context.Context, entities.Query) (int64, error)) *MockWateringPlanRepository_GetCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvaluationValues provides a mock function with given fields: ctx, id
func (_m *MockWateringPlanRepository) GetEvaluationValues(ctx context.Context, id int32) ([]*entities.EvaluationValue, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEvaluationValues")
	}

	var r0 []*entities.EvaluationValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]*entities.EvaluationValue, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []*entities.EvaluationValue); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.EvaluationValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetEvaluationValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvaluationValues'
type MockWateringPlanRepository_GetEvaluationValues_Call struct {
	*mock.Call
}

// GetEvaluationValues is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWateringPlanRepository_Expecter) GetEvaluationValues(ctx interface{}, id interface{}) *MockWateringPlanRepository_GetEvaluationValues_Call {
	return &MockWateringPlanRepository_GetEvaluationValues_Call{Call: _e.mock.On("GetEvaluationValues", ctx, id)}
}

func (_c *MockWateringPlanRepository_GetEvaluationValues_Call) Run(run func(ctx context.Context, id int32)) *MockWateringPlanRepository_GetEvaluationValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetEvaluationValues_Call) Return(_a0 []*entities.EvaluationValue, _a1 error) *MockWateringPlanRepository_GetEvaluationValues_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetEvaluationValues_Call) RunAndReturn(run func(context.Context, int32) ([]*entities.EvaluationValue, error)) *MockWateringPlanRepository_GetEvaluationValues_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkedTreeClustersByID provides a mock function with given fields: ctx, id
func (_m *MockWateringPlanRepository) GetLinkedTreeClustersByID(ctx context.Context, id int32) ([]*entities.TreeCluster, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkedTreeClustersByID")
	}

	var r0 []*entities.TreeCluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]*entities.TreeCluster, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []*entities.TreeCluster); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.TreeCluster)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetLinkedTreeClustersByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkedTreeClustersByID'
type MockWateringPlanRepository_GetLinkedTreeClustersByID_Call struct {
	*mock.Call
}

// GetLinkedTreeClustersByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWateringPlanRepository_Expecter) GetLinkedTreeClustersByID(ctx interface{}, id interface{}) *MockWateringPlanRepository_GetLinkedTreeClustersByID_Call {
	return &MockWateringPlanRepository_GetLinkedTreeClustersByID_Call{Call: _e.mock.On("GetLinkedTreeClustersByID", ctx, id)}
}

func (_c *MockWateringPlanRepository_GetLinkedTreeClustersByID_Call) Run(run func(ctx context.Context, id int32)) *MockWateringPlanRepository_GetLinkedTreeClustersByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetLinkedTreeClustersByID_Call) Return(_a0 []*entities.TreeCluster, _a1 error) *MockWateringPlanRepository_GetLinkedTreeClustersByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetLinkedTreeClustersByID_Call) RunAndReturn(run func(context.Context, int32) ([]*entities.TreeCluster, error)) *MockWateringPlanRepository_GetLinkedTreeClustersByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkedUsersByID provides a mock function with given fields: ctx, id
func (_m *MockWateringPlanRepository) GetLinkedUsersByID(ctx context.Context, id int32) ([]*uuid.UUID, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkedUsersByID")
	}

	var r0 []*uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]*uuid.UUID, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []*uuid.UUID); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetLinkedUsersByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkedUsersByID'
type MockWateringPlanRepository_GetLinkedUsersByID_Call struct {
	*mock.Call
}

// GetLinkedUsersByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWateringPlanRepository_Expecter) GetLinkedUsersByID(ctx interface{}, id interface{}) *MockWateringPlanRepository_GetLinkedUsersByID_Call {
	return &MockWateringPlanRepository_GetLinkedUsersByID_Call{Call: _e.mock.On("GetLinkedUsersByID", ctx, id)}
}

func (_c *MockWateringPlanRepository_GetLinkedUsersByID_Call) Run(run func(ctx context.Context, id int32)) *MockWateringPlanRepository_GetLinkedUsersByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetLinkedUsersByID_Call) Return(_a0 []*uuid.UUID, _a1 error) *MockWateringPlanRepository_GetLinkedUsersByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetLinkedUsersByID_Call) RunAndReturn(run func(context.Context, int32) ([]*uuid.UUID, error)) *MockWateringPlanRepository_GetLinkedUsersByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLinkedVehicleByIDAndType provides a mock function with given fields: ctx, id, vehicleType
func (_m *MockWateringPlanRepository) GetLinkedVehicleByIDAndType(ctx context.Context, id int32, vehicleType entities.VehicleType) (*entities.Vehicle, error) {
	ret := _m.Called(ctx, id, vehicleType)

	if len(ret) == 0 {
		panic("no return value specified for GetLinkedVehicleByIDAndType")
	}

	var r0 *entities.Vehicle
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, entities.VehicleType) (*entities.Vehicle, error)); ok {
		return rf(ctx, id, vehicleType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, entities.VehicleType) *entities.Vehicle); ok {
		r0 = rf(ctx, id, vehicleType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Vehicle)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, entities.VehicleType) error); ok {
		r1 = rf(ctx, id, vehicleType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLinkedVehicleByIDAndType'
type MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call struct {
	*mock.Call
}

// GetLinkedVehicleByIDAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - vehicleType entities.VehicleType
func (_e *MockWateringPlanRepository_Expecter) GetLinkedVehicleByIDAndType(ctx interface{}, id interface{}, vehicleType interface{}) *MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call {
	return &MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call{Call: _e.mock.On("GetLinkedVehicleByIDAndType", ctx, id, vehicleType)}
}

func (_c *MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call) Run(run func(ctx context.Context, id int32, vehicleType entities.VehicleType)) *MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(entities.VehicleType))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call) Return(_a0 *entities.Vehicle, _a1 error) *MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call) RunAndReturn(run func(context.Context, int32, entities.VehicleType) (*entities.Vehicle, error)) *MockWateringPlanRepository_GetLinkedVehicleByIDAndType_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalConsumedWater provides a mock function with given fields: ctx
func (_m *MockWateringPlanRepository) GetTotalConsumedWater(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalConsumedWater")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetTotalConsumedWater_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalConsumedWater'
type MockWateringPlanRepository_GetTotalConsumedWater_Call struct {
	*mock.Call
}

// GetTotalConsumedWater is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWateringPlanRepository_Expecter) GetTotalConsumedWater(ctx interface{}) *MockWateringPlanRepository_GetTotalConsumedWater_Call {
	return &MockWateringPlanRepository_GetTotalConsumedWater_Call{Call: _e.mock.On("GetTotalConsumedWater", ctx)}
}

func (_c *MockWateringPlanRepository_GetTotalConsumedWater_Call) Run(run func(ctx context.Context)) *MockWateringPlanRepository_GetTotalConsumedWater_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetTotalConsumedWater_Call) Return(_a0 int64, _a1 error) *MockWateringPlanRepository_GetTotalConsumedWater_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetTotalConsumedWater_Call) RunAndReturn(run func(context.Context) (int64, error)) *MockWateringPlanRepository_GetTotalConsumedWater_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, fn
func (_m *MockWateringPlanRepository) Update(ctx context.Context, id int32, fn func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)) error {
	ret := _m.Called(ctx, id, fn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)) error); ok {
		r0 = rf(ctx, id, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWateringPlanRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWateringPlanRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - fn func(*entities.WateringPlan , storage.WateringPlanRepository)(bool , error)
func (_e *MockWateringPlanRepository_Expecter) Update(ctx interface{}, id interface{}, fn interface{}) *MockWateringPlanRepository_Update_Call {
	return &MockWateringPlanRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, fn)}
}

func (_c *MockWateringPlanRepository_Update_Call) Run(run func(ctx context.Context, id int32, fn func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error))) *MockWateringPlanRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)))
	})
	return _c
}

func (_c *MockWateringPlanRepository_Update_Call) Return(_a0 error) *MockWateringPlanRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWateringPlanRepository_Update_Call) RunAndReturn(run func(context.Context, int32, func(*entities.WateringPlan, storage.WateringPlanRepository) (bool, error)) error) *MockWateringPlanRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWateringPlanRepository creates a new instance of MockWateringPlanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWateringPlanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWateringPlanRepository {
	mock := &MockWateringPlanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
