// Code generated by mockery v2.52.2. DO NOT EDIT.

package service

import (
	context "context"
	io "io"

	entities "github.com/green-ecolution/backend/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockWateringPlanService is an autogenerated mock type for the WateringPlanService type
type MockWateringPlanService struct {
	mock.Mock
}

type MockWateringPlanService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWateringPlanService) EXPECT() *MockWateringPlanService_Expecter {
	return &MockWateringPlanService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, createData
func (_m *MockWateringPlanService) Create(ctx context.Context, createData *entities.WateringPlanCreate) (*entities.WateringPlan, error) {
	ret := _m.Called(ctx, createData)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.WateringPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.WateringPlanCreate) (*entities.WateringPlan, error)); ok {
		return rf(ctx, createData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entities.WateringPlanCreate) *entities.WateringPlan); ok {
		r0 = rf(ctx, createData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entities.WateringPlanCreate) error); ok {
		r1 = rf(ctx, createData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWateringPlanService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - createData *entities.WateringPlanCreate
func (_e *MockWateringPlanService_Expecter) Create(ctx interface{}, createData interface{}) *MockWateringPlanService_Create_Call {
	return &MockWateringPlanService_Create_Call{Call: _e.mock.On("Create", ctx, createData)}
}

func (_c *MockWateringPlanService_Create_Call) Run(run func(ctx context.Context, createData *entities.WateringPlanCreate)) *MockWateringPlanService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.WateringPlanCreate))
	})
	return _c
}

func (_c *MockWateringPlanService_Create_Call) Return(_a0 *entities.WateringPlan, _a1 error) *MockWateringPlanService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanService_Create_Call) RunAndReturn(run func(context.Context, *entities.WateringPlanCreate) (*entities.WateringPlan, error)) *MockWateringPlanService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockWateringPlanService) Delete(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWateringPlanService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWateringPlanService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWateringPlanService_Expecter) Delete(ctx interface{}, id interface{}) *MockWateringPlanService_Delete_Call {
	return &MockWateringPlanService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockWateringPlanService_Delete_Call) Run(run func(ctx context.Context, id int32)) *MockWateringPlanService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWateringPlanService_Delete_Call) Return(_a0 error) *MockWateringPlanService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWateringPlanService_Delete_Call) RunAndReturn(run func(context.Context, int32) error) *MockWateringPlanService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, query
func (_m *MockWateringPlanService) GetAll(ctx context.Context, query entities.Query) ([]*entities.WateringPlan, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*entities.WateringPlan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Query) ([]*entities.WateringPlan, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Query) []*entities.WateringPlan); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Query) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entities.Query) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWateringPlanService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockWateringPlanService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - query entities.Query
func (_e *MockWateringPlanService_Expecter) GetAll(ctx interface{}, query interface{}) *MockWateringPlanService_GetAll_Call {
	return &MockWateringPlanService_GetAll_Call{Call: _e.mock.On("GetAll", ctx, query)}
}

func (_c *MockWateringPlanService_GetAll_Call) Run(run func(ctx context.Context, query entities.Query)) *MockWateringPlanService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entities.Query))
	})
	return _c
}

func (_c *MockWateringPlanService_GetAll_Call) Return(_a0 []*entities.WateringPlan, _a1 int64, _a2 error) *MockWateringPlanService_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockWateringPlanService_GetAll_Call) RunAndReturn(run func(context.Context, entities.Query) ([]*entities.WateringPlan, int64, error)) *MockWateringPlanService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockWateringPlanService) GetByID(ctx context.Context, id int32) (*entities.WateringPlan, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.WateringPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*entities.WateringPlan, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *entities.WateringPlan); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWateringPlanService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWateringPlanService_Expecter) GetByID(ctx interface{}, id interface{}) *MockWateringPlanService_GetByID_Call {
	return &MockWateringPlanService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockWateringPlanService_GetByID_Call) Run(run func(ctx context.Context, id int32)) *MockWateringPlanService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWateringPlanService_GetByID_Call) Return(_a0 *entities.WateringPlan, _a1 error) *MockWateringPlanService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanService_GetByID_Call) RunAndReturn(run func(context.Context, int32) (*entities.WateringPlan, error)) *MockWateringPlanService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGPXFileStream provides a mock function with given fields: ctx, objName
func (_m *MockWateringPlanService) GetGPXFileStream(ctx context.Context, objName string) (io.ReadSeekCloser, error) {
	ret := _m.Called(ctx, objName)

	if len(ret) == 0 {
		panic("no return value specified for GetGPXFileStream")
	}

	var r0 io.ReadSeekCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadSeekCloser, error)); ok {
		return rf(ctx, objName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadSeekCloser); ok {
		r0 = rf(ctx, objName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeekCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanService_GetGPXFileStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGPXFileStream'
type MockWateringPlanService_GetGPXFileStream_Call struct {
	*mock.Call
}

// GetGPXFileStream is a helper method to define mock.On call
//   - ctx context.Context
//   - objName string
func (_e *MockWateringPlanService_Expecter) GetGPXFileStream(ctx interface{}, objName interface{}) *MockWateringPlanService_GetGPXFileStream_Call {
	return &MockWateringPlanService_GetGPXFileStream_Call{Call: _e.mock.On("GetGPXFileStream", ctx, objName)}
}

func (_c *MockWateringPlanService_GetGPXFileStream_Call) Run(run func(ctx context.Context, objName string)) *MockWateringPlanService_GetGPXFileStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWateringPlanService_GetGPXFileStream_Call) Return(_a0 io.ReadSeekCloser, _a1 error) *MockWateringPlanService_GetGPXFileStream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanService_GetGPXFileStream_Call) RunAndReturn(run func(context.Context, string) (io.ReadSeekCloser, error)) *MockWateringPlanService_GetGPXFileStream_Call {
	_c.Call.Return(run)
	return _c
}

// PreviewRoute provides a mock function with given fields: ctx, transporterID, trailerID, clusterIDs
func (_m *MockWateringPlanService) PreviewRoute(ctx context.Context, transporterID int32, trailerID *int32, clusterIDs []int32) (*entities.GeoJSON, error) {
	ret := _m.Called(ctx, transporterID, trailerID, clusterIDs)

	if len(ret) == 0 {
		panic("no return value specified for PreviewRoute")
	}

	var r0 *entities.GeoJSON
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, *int32, []int32) (*entities.GeoJSON, error)); ok {
		return rf(ctx, transporterID, trailerID, clusterIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, *int32, []int32) *entities.GeoJSON); ok {
		r0 = rf(ctx, transporterID, trailerID, clusterIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GeoJSON)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, *int32, []int32) error); ok {
		r1 = rf(ctx, transporterID, trailerID, clusterIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanService_PreviewRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreviewRoute'
type MockWateringPlanService_PreviewRoute_Call struct {
	*mock.Call
}

// PreviewRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - transporterID int32
//   - trailerID *int32
//   - clusterIDs []int32
func (_e *MockWateringPlanService_Expecter) PreviewRoute(ctx interface{}, transporterID interface{}, trailerID interface{}, clusterIDs interface{}) *MockWateringPlanService_PreviewRoute_Call {
	return &MockWateringPlanService_PreviewRoute_Call{Call: _e.mock.On("PreviewRoute", ctx, transporterID, trailerID, clusterIDs)}
}

func (_c *MockWateringPlanService_PreviewRoute_Call) Run(run func(ctx context.Context, transporterID int32, trailerID *int32, clusterIDs []int32)) *MockWateringPlanService_PreviewRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(*int32), args[3].([]int32))
	})
	return _c
}

func (_c *MockWateringPlanService_PreviewRoute_Call) Return(_a0 *entities.GeoJSON, _a1 error) *MockWateringPlanService_PreviewRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanService_PreviewRoute_Call) RunAndReturn(run func(context.Context, int32, *int32, []int32) (*entities.GeoJSON, error)) *MockWateringPlanService_PreviewRoute_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with no fields
func (_m *MockWateringPlanService) Ready() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockWateringPlanService_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockWateringPlanService_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *MockWateringPlanService_Expecter) Ready() *MockWateringPlanService_Ready_Call {
	return &MockWateringPlanService_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *MockWateringPlanService_Ready_Call) Run(run func()) *MockWateringPlanService_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWateringPlanService_Ready_Call) Return(_a0 bool) *MockWateringPlanService_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWateringPlanService_Ready_Call) RunAndReturn(run func() bool) *MockWateringPlanService_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updateData
func (_m *MockWateringPlanService) Update(ctx context.Context, id int32, updateData *entities.WateringPlanUpdate) (*entities.WateringPlan, error) {
	ret := _m.Called(ctx, id, updateData)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.WateringPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, *entities.WateringPlanUpdate) (*entities.WateringPlan, error)); ok {
		return rf(ctx, id, updateData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, *entities.WateringPlanUpdate) *entities.WateringPlan); ok {
		r0 = rf(ctx, id, updateData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, *entities.WateringPlanUpdate) error); ok {
		r1 = rf(ctx, id, updateData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWateringPlanService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - updateData *entities.WateringPlanUpdate
func (_e *MockWateringPlanService_Expecter) Update(ctx interface{}, id interface{}, updateData interface{}) *MockWateringPlanService_Update_Call {
	return &MockWateringPlanService_Update_Call{Call: _e.mock.On("Update", ctx, id, updateData)}
}

func (_c *MockWateringPlanService_Update_Call) Run(run func(ctx context.Context, id int32, updateData *entities.WateringPlanUpdate)) *MockWateringPlanService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(*entities.WateringPlanUpdate))
	})
	return _c
}

func (_c *MockWateringPlanService_Update_Call) Return(_a0 *entities.WateringPlan, _a1 error) *MockWateringPlanService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanService_Update_Call) RunAndReturn(run func(context.Context, int32, *entities.WateringPlanUpdate) (*entities.WateringPlan, error)) *MockWateringPlanService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatuses provides a mock function with given fields: ctx
func (_m *MockWateringPlanService) UpdateStatuses(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatuses")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWateringPlanService_UpdateStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatuses'
type MockWateringPlanService_UpdateStatuses_Call struct {
	*mock.Call
}

// UpdateStatuses is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWateringPlanService_Expecter) UpdateStatuses(ctx interface{}) *MockWateringPlanService_UpdateStatuses_Call {
	return &MockWateringPlanService_UpdateStatuses_Call{Call: _e.mock.On("UpdateStatuses", ctx)}
}

func (_c *MockWateringPlanService_UpdateStatuses_Call) Run(run func(ctx context.Context)) *MockWateringPlanService_UpdateStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWateringPlanService_UpdateStatuses_Call) Return(_a0 error) *MockWateringPlanService_UpdateStatuses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWateringPlanService_UpdateStatuses_Call) RunAndReturn(run func(context.Context) error) *MockWateringPlanService_UpdateStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWateringPlanService creates a new instance of MockWateringPlanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWateringPlanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWateringPlanService {
	mock := &MockWateringPlanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
