// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: region.sql

package sqlc

import (
	"context"
)

const createRegion = `-- name: CreateRegion :one
INSERT INTO regions (name, geometry) VALUES ($1, ST_GeomFromText($2, 4326)) RETURNING id
`

type CreateRegionParams struct {
	Name           string
	StGeomfromtext interface{}
}

func (q *Queries) CreateRegion(ctx context.Context, arg *CreateRegionParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRegion, arg.Name, arg.StGeomfromtext)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteRegion = `-- name: DeleteRegion :exec
DELETE FROM regions WHERE id = $1
`

func (q *Queries) DeleteRegion(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRegion, id)
	return err
}

const getAllRegions = `-- name: GetAllRegions :many
SELECT id, name, created_at, updated_at, geometry FROM regions 
ORDER BY id 
LIMIT $1 OFFSET $2
`

type GetAllRegionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllRegions(ctx context.Context, arg *GetAllRegionsParams) ([]*Region, error) {
	rows, err := q.db.Query(ctx, getAllRegions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Region{}
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Geometry,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRegionsCount = `-- name: GetAllRegionsCount :one
SELECT COUNT(*) FROM regions
`

func (q *Queries) GetAllRegionsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAllRegionsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRegionById = `-- name: GetRegionById :one
SELECT id, name, created_at, updated_at, geometry FROM regions WHERE id = $1
`

func (q *Queries) GetRegionById(ctx context.Context, id int32) (*Region, error) {
	row := q.db.QueryRow(ctx, getRegionById, id)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Geometry,
	)
	return &i, err
}

const getRegionByName = `-- name: GetRegionByName :one
SELECT id, name, created_at, updated_at, geometry FROM regions WHERE name = $1
`

func (q *Queries) GetRegionByName(ctx context.Context, name string) (*Region, error) {
	row := q.db.QueryRow(ctx, getRegionByName, name)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Geometry,
	)
	return &i, err
}

const getRegionByPoint = `-- name: GetRegionByPoint :one
SELECT id, name, created_at, updated_at, geometry FROM regions WHERE ST_Contains(geometry, ST_GeomFromText($1, 4326))
`

func (q *Queries) GetRegionByPoint(ctx context.Context, stGeomfromtext interface{}) (*Region, error) {
	row := q.db.QueryRow(ctx, getRegionByPoint, stGeomfromtext)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Geometry,
	)
	return &i, err
}

const updateRegion = `-- name: UpdateRegion :exec
UPDATE regions SET name = $2, geometry = ST_GeomFromText($3, 4326) WHERE id = $1
`

type UpdateRegionParams struct {
	ID             int32
	Name           string
	StGeomfromtext interface{}
}

func (q *Queries) UpdateRegion(ctx context.Context, arg *UpdateRegionParams) error {
	_, err := q.db.Exec(ctx, updateRegion, arg.ID, arg.Name, arg.StGeomfromtext)
	return err
}
