/*
Green Space Management API

This is the API for the Green Ecolution Management System.

API version: develop
Contact: info@green-ecolution.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DataStatistics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataStatistics{}

// DataStatistics struct for DataStatistics
type DataStatistics struct {
	SensorCount       int32 `json:"sensorCount"`
	TreeClusterCount  int32 `json:"treeClusterCount"`
	TreeCount         int32 `json:"treeCount"`
	VehicleCount      int32 `json:"vehicleCount"`
	WateringPlanCount int32 `json:"wateringPlanCount"`
}

type _DataStatistics DataStatistics

// NewDataStatistics instantiates a new DataStatistics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataStatistics(sensorCount int32, treeClusterCount int32, treeCount int32, vehicleCount int32, wateringPlanCount int32) *DataStatistics {
	this := DataStatistics{}
	this.SensorCount = sensorCount
	this.TreeClusterCount = treeClusterCount
	this.TreeCount = treeCount
	this.VehicleCount = vehicleCount
	this.WateringPlanCount = wateringPlanCount
	return &this
}

// NewDataStatisticsWithDefaults instantiates a new DataStatistics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataStatisticsWithDefaults() *DataStatistics {
	this := DataStatistics{}
	return &this
}

// GetSensorCount returns the SensorCount field value
func (o *DataStatistics) GetSensorCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SensorCount
}

// GetSensorCountOk returns a tuple with the SensorCount field value
// and a boolean to check if the value has been set.
func (o *DataStatistics) GetSensorCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SensorCount, true
}

// SetSensorCount sets field value
func (o *DataStatistics) SetSensorCount(v int32) {
	o.SensorCount = v
}

// GetTreeClusterCount returns the TreeClusterCount field value
func (o *DataStatistics) GetTreeClusterCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TreeClusterCount
}

// GetTreeClusterCountOk returns a tuple with the TreeClusterCount field value
// and a boolean to check if the value has been set.
func (o *DataStatistics) GetTreeClusterCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TreeClusterCount, true
}

// SetTreeClusterCount sets field value
func (o *DataStatistics) SetTreeClusterCount(v int32) {
	o.TreeClusterCount = v
}

// GetTreeCount returns the TreeCount field value
func (o *DataStatistics) GetTreeCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TreeCount
}

// GetTreeCountOk returns a tuple with the TreeCount field value
// and a boolean to check if the value has been set.
func (o *DataStatistics) GetTreeCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TreeCount, true
}

// SetTreeCount sets field value
func (o *DataStatistics) SetTreeCount(v int32) {
	o.TreeCount = v
}

// GetVehicleCount returns the VehicleCount field value
func (o *DataStatistics) GetVehicleCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VehicleCount
}

// GetVehicleCountOk returns a tuple with the VehicleCount field value
// and a boolean to check if the value has been set.
func (o *DataStatistics) GetVehicleCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VehicleCount, true
}

// SetVehicleCount sets field value
func (o *DataStatistics) SetVehicleCount(v int32) {
	o.VehicleCount = v
}

// GetWateringPlanCount returns the WateringPlanCount field value
func (o *DataStatistics) GetWateringPlanCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WateringPlanCount
}

// GetWateringPlanCountOk returns a tuple with the WateringPlanCount field value
// and a boolean to check if the value has been set.
func (o *DataStatistics) GetWateringPlanCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WateringPlanCount, true
}

// SetWateringPlanCount sets field value
func (o *DataStatistics) SetWateringPlanCount(v int32) {
	o.WateringPlanCount = v
}

func (o DataStatistics) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataStatistics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sensorCount"] = o.SensorCount
	toSerialize["treeClusterCount"] = o.TreeClusterCount
	toSerialize["treeCount"] = o.TreeCount
	toSerialize["vehicleCount"] = o.VehicleCount
	toSerialize["wateringPlanCount"] = o.WateringPlanCount
	return toSerialize, nil
}

func (o *DataStatistics) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sensorCount",
		"treeClusterCount",
		"treeCount",
		"vehicleCount",
		"wateringPlanCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataStatistics := _DataStatistics{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDataStatistics)

	if err != nil {
		return err
	}

	*o = DataStatistics(varDataStatistics)

	return err
}

type NullableDataStatistics struct {
	value *DataStatistics
	isSet bool
}

func (v NullableDataStatistics) Get() *DataStatistics {
	return v.value
}

func (v *NullableDataStatistics) Set(val *DataStatistics) {
	v.value = val
	v.isSet = true
}

func (v NullableDataStatistics) IsSet() bool {
	return v.isSet
}

func (v *NullableDataStatistics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataStatistics(val *DataStatistics) *NullableDataStatistics {
	return &NullableDataStatistics{value: val, isSet: true}
}

func (v NullableDataStatistics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataStatistics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
