/*
Green Space Management API

This is the API for the Green Ecolution Management System.

API version: develop
Contact: info@green-ecolution.de
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TreeWithDistance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TreeWithDistance{}

// TreeWithDistance struct for TreeWithDistance
type TreeWithDistance struct {
	DistanceMeters float32 `json:"distance_meters"`
	Tree           Tree    `json:"tree"`
}

type _TreeWithDistance TreeWithDistance

// NewTreeWithDistance instantiates a new TreeWithDistance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTreeWithDistance(distanceMeters float32, tree Tree) *TreeWithDistance {
	this := TreeWithDistance{}
	this.DistanceMeters = distanceMeters
	this.Tree = tree
	return &this
}

// NewTreeWithDistanceWithDefaults instantiates a new TreeWithDistance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTreeWithDistanceWithDefaults() *TreeWithDistance {
	this := TreeWithDistance{}
	return &this
}

// GetDistanceMeters returns the DistanceMeters field value
func (o *TreeWithDistance) GetDistanceMeters() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DistanceMeters
}

// GetDistanceMetersOk returns a tuple with the DistanceMeters field value
// and a boolean to check if the value has been set.
func (o *TreeWithDistance) GetDistanceMetersOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistanceMeters, true
}

// SetDistanceMeters sets field value
func (o *TreeWithDistance) SetDistanceMeters(v float32) {
	o.DistanceMeters = v
}

// GetTree returns the Tree field value
func (o *TreeWithDistance) GetTree() Tree {
	if o == nil {
		var ret Tree
		return ret
	}

	return o.Tree
}

// GetTreeOk returns a tuple with the Tree field value
// and a boolean to check if the value has been set.
func (o *TreeWithDistance) GetTreeOk() (*Tree, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tree, true
}

// SetTree sets field value
func (o *TreeWithDistance) SetTree(v Tree) {
	o.Tree = v
}

func (o TreeWithDistance) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TreeWithDistance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["distance_meters"] = o.DistanceMeters
	toSerialize["tree"] = o.Tree
	return toSerialize, nil
}

func (o *TreeWithDistance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"distance_meters",
		"tree",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTreeWithDistance := _TreeWithDistance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTreeWithDistance)

	if err != nil {
		return err
	}

	*o = TreeWithDistance(varTreeWithDistance)

	return err
}

type NullableTreeWithDistance struct {
	value *TreeWithDistance
	isSet bool
}

func (v NullableTreeWithDistance) Get() *TreeWithDistance {
	return v.value
}

func (v *NullableTreeWithDistance) Set(val *TreeWithDistance) {
	v.value = val
	v.isSet = true
}

func (v NullableTreeWithDistance) IsSet() bool {
	return v.isSet
}

func (v *NullableTreeWithDistance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTreeWithDistance(val *TreeWithDistance) *NullableTreeWithDistance {
	return &NullableTreeWithDistance{value: val, isSet: true}
}

func (v NullableTreeWithDistance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTreeWithDistance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
