/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppInfoResponse,
  DataStatisticsResponse,
  ErrorBody,
  MapInfoResponse,
  ReadinessResponse,
  ServerInfoResponse,
  ServicesInfoResponse,
} from '../models/index';
import {
    AppInfoResponseFromJSON,
    AppInfoResponseToJSON,
    DataStatisticsResponseFromJSON,
    DataStatisticsResponseToJSON,
    ErrorBodyFromJSON,
    ErrorBodyToJSON,
    MapInfoResponseFromJSON,
    MapInfoResponseToJSON,
    ReadinessResponseFromJSON,
    ReadinessResponseToJSON,
    ServerInfoResponseFromJSON,
    ServerInfoResponseToJSON,
    ServicesInfoResponseFromJSON,
    ServicesInfoResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class InfoApi extends runtime.BaseAPI {

    /**
     * Creates request options for getInfo without sending the request
     */
    async getInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/info`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns version, git, and map configuration metadata.
     * Get application info
     */
    async getInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInfoResponse>> {
        const requestOptions = await this.getInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppInfoResponseFromJSON(jsonValue));
    }

    /**
     * Returns version, git, and map configuration metadata.
     * Get application info
     */
    async getInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInfoResponse> {
        const response = await this.getInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMapInfo without sending the request
     */
    async getMapInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/info/map`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the map center coordinates and bounding box.
     * Get map configuration
     */
    async getMapInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MapInfoResponse>> {
        const requestOptions = await this.getMapInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MapInfoResponseFromJSON(jsonValue));
    }

    /**
     * Returns the map center coordinates and bounding box.
     * Get map configuration
     */
    async getMapInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MapInfoResponse> {
        const response = await this.getMapInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getServerInfo without sending the request
     */
    async getServerInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/info/server`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns server OS, hostname, and network information.
     * Get server info
     */
    async getServerInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServerInfoResponse>> {
        const requestOptions = await this.getServerInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerInfoResponseFromJSON(jsonValue));
    }

    /**
     * Returns server OS, hostname, and network information.
     * Get server info
     */
    async getServerInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServerInfoResponse> {
        const response = await this.getServerInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getServicesInfo without sending the request
     */
    async getServicesInfoRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/info/services`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns health status of all connected services (database, routing, etc.).
     * Get services health
     */
    async getServicesInfoRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicesInfoResponse>> {
        const requestOptions = await this.getServicesInfoRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicesInfoResponseFromJSON(jsonValue));
    }

    /**
     * Returns health status of all connected services (database, routing, etc.).
     * Get services health
     */
    async getServicesInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicesInfoResponse> {
        const response = await this.getServicesInfoRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStatistics without sending the request
     */
    async getStatisticsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/info/statistics`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns counts of all managed resources.
     * Get data statistics
     */
    async getStatisticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataStatisticsResponse>> {
        const requestOptions = await this.getStatisticsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataStatisticsResponseFromJSON(jsonValue));
    }

    /**
     * Returns counts of all managed resources.
     * Get data statistics
     */
    async getStatistics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataStatisticsResponse> {
        const response = await this.getStatisticsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for health without sending the request
     */
    async healthRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lightweight liveness probe for container orchestrators. Returns 200 OK while the HTTP server is responsive; performs no downstream service checks. Use /api/ready for a readiness probe that verifies critical dependencies, or /api/v1/info/services for a deep services health check.
     * Liveness probe
     */
    async healthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.healthRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Lightweight liveness probe for container orchestrators. Returns 200 OK while the HTTP server is responsive; performs no downstream service checks. Use /api/ready for a readiness probe that verifies critical dependencies, or /api/v1/info/services for a deep services health check.
     * Liveness probe
     */
    async health(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.healthRaw(initOverrides);
    }

    /**
     * Creates request options for readiness without sending the request
     */
    async readinessRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ready`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Readiness probe for container orchestrators. Verifies that critical dependencies (the database) are reachable and returns 200 only when the service can serve traffic; returns 503 otherwise so the pod is pulled from the load balancer. Optional services (auth, MQTT) are reported by /api/v1/info/services and do not gate readiness.
     * Readiness probe
     */
    async readinessRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadinessResponse>> {
        const requestOptions = await this.readinessRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadinessResponseFromJSON(jsonValue));
    }

    /**
     * Readiness probe for container orchestrators. Verifies that critical dependencies (the database) are reachable and returns 200 only when the service can serve traffic; returns 503 otherwise so the pod is pulled from the load balancer. Optional services (auth, MQTT) are reported by /api/v1/info/services and do not gate readiness.
     * Readiness probe
     */
    async readiness(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadinessResponse> {
        const response = await this.readinessRaw(initOverrides);
        return await response.value();
    }

}
