/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-45-gbbcdc5fa-dirty
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPError,
  Region,
  RegionList,
} from '../models/index';
import {
    HTTPErrorFromJSON,
    HTTPErrorToJSON,
    RegionFromJSON,
    RegionToJSON,
    RegionListFromJSON,
    RegionListToJSON,
} from '../models/index';

export interface GetAllRegionsRequest {
    page?: number;
    limit?: number;
}

export interface GetRegionByIdRequest {
    id: number;
}

/**
 * 
 */
export class RegionApi extends runtime.BaseAPI {

    /**
     * Retrieves a list of all available regions for tree cluster assignment.
     * Get all regions
     */
    async getAllRegionsRaw(requestParameters: GetAllRegionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegionList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/region`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegionListFromJSON(jsonValue));
    }

    /**
     * Retrieves a list of all available regions for tree cluster assignment.
     * Get all regions
     */
    async getAllRegions(requestParameters: GetAllRegionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegionList> {
        const response = await this.getAllRegionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves detailed information about a specific region.
     * Get a region by ID
     */
    async getRegionByIdRaw(requestParameters: GetRegionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Region>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRegionById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/region/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegionFromJSON(jsonValue));
    }

    /**
     * Retrieves detailed information about a specific region.
     * Get a region by ID
     */
    async getRegionById(requestParameters: GetRegionByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Region> {
        const response = await this.getRegionByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
