/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v1.2.0-37-g1c5af7f8-stage
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPError,
  Tree,
  TreeCreate,
  TreeList,
  TreeUpdate,
} from '../models/index';
import {
    HTTPErrorFromJSON,
    HTTPErrorToJSON,
    TreeFromJSON,
    TreeToJSON,
    TreeCreateFromJSON,
    TreeCreateToJSON,
    TreeListFromJSON,
    TreeListToJSON,
    TreeUpdateFromJSON,
    TreeUpdateToJSON,
} from '../models/index';

export interface CreateTreeRequest {
    body: TreeCreate;
}

export interface DeleteTreeRequest {
    treeId: number;
}

export interface GetAllTreesRequest {
    page?: number;
    limit?: number;
    provider?: string;
    wateringStatuses?: Array<string>;
    plantingYears?: Array<number>;
    hasCluster?: boolean;
}

export interface GetTreesRequest {
    treeId: number;
}

export interface UpdateTreeRequest {
    treeId: number;
    body: TreeUpdate;
}

/**
 * 
 */
export class TreeApi extends runtime.BaseAPI {

    /**
     * Create tree
     * Create tree
     */
    async createTreeRaw(requestParameters: CreateTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Tree>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/tree`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TreeCreateToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeFromJSON(jsonValue));
    }

    /**
     * Create tree
     * Create tree
     */
    async createTree(requestParameters: CreateTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Tree> {
        const response = await this.createTreeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete tree
     * Delete tree
     */
    async deleteTreeRaw(requestParameters: DeleteTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['treeId'] == null) {
            throw new runtime.RequiredError(
                'treeId',
                'Required parameter "treeId" was null or undefined when calling deleteTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/tree/{tree_id}`;
        urlPath = urlPath.replace(`{${"tree_id"}}`, encodeURIComponent(String(requestParameters['treeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete tree
     * Delete tree
     */
    async deleteTree(requestParameters: DeleteTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTreeRaw(requestParameters, initOverrides);
    }

    /**
     * Get all trees
     * Get all trees
     */
    async getAllTreesRaw(requestParameters: GetAllTreesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['wateringStatuses'] != null) {
            queryParameters['watering_statuses'] = requestParameters['wateringStatuses']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['plantingYears'] != null) {
            queryParameters['planting_years'] = requestParameters['plantingYears']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['hasCluster'] != null) {
            queryParameters['has_cluster'] = requestParameters['hasCluster'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/tree`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeListFromJSON(jsonValue));
    }

    /**
     * Get all trees
     * Get all trees
     */
    async getAllTrees(requestParameters: GetAllTreesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeList> {
        const response = await this.getAllTreesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get tree by ID
     * Get tree by ID
     */
    async getTreesRaw(requestParameters: GetTreesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Tree>> {
        if (requestParameters['treeId'] == null) {
            throw new runtime.RequiredError(
                'treeId',
                'Required parameter "treeId" was null or undefined when calling getTrees().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/tree/{tree_id}`;
        urlPath = urlPath.replace(`{${"tree_id"}}`, encodeURIComponent(String(requestParameters['treeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeFromJSON(jsonValue));
    }

    /**
     * Get tree by ID
     * Get tree by ID
     */
    async getTrees(requestParameters: GetTreesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Tree> {
        const response = await this.getTreesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update tree
     * Update tree
     */
    async updateTreeRaw(requestParameters: UpdateTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Tree>> {
        if (requestParameters['treeId'] == null) {
            throw new runtime.RequiredError(
                'treeId',
                'Required parameter "treeId" was null or undefined when calling updateTree().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateTree().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/tree/{tree_id}`;
        urlPath = urlPath.replace(`{${"tree_id"}}`, encodeURIComponent(String(requestParameters['treeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TreeUpdateToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeFromJSON(jsonValue));
    }

    /**
     * Update tree
     * Update tree
     */
    async updateTree(requestParameters: UpdateTreeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Tree> {
        const response = await this.updateTreeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
