/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution API
 * REST API for the Green Ecolution smart irrigation and green-space management platform. Combines IoT sensor data, route optimization, and automated maintenance scheduling to help municipalities manage urban greenery efficiently. The system uses LoRaWAN sensors to monitor soil conditions, calculates optimal watering routes, and provides fleet management capabilities.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ClusterMarkerListResponse,
  ListResponseTreeClusterInListResponse,
  TreeClusterCreateRequest,
  TreeClusterResponse,
  TreeClusterUpdateRequest,
} from '../models/index';
import {
    ClusterMarkerListResponseFromJSON,
    ClusterMarkerListResponseToJSON,
    ListResponseTreeClusterInListResponseFromJSON,
    ListResponseTreeClusterInListResponseToJSON,
    TreeClusterCreateRequestFromJSON,
    TreeClusterCreateRequestToJSON,
    TreeClusterResponseFromJSON,
    TreeClusterResponseToJSON,
    TreeClusterUpdateRequestFromJSON,
    TreeClusterUpdateRequestToJSON,
} from '../models/index';

export interface CreateClusterRequest {
    treeClusterCreateRequest: TreeClusterCreateRequest;
}

export interface DeleteClusterRequest {
    clusterId: string;
}

export interface GetClusterRequest {
    clusterId: string;
}

export interface ListClustersRequest {
    page?: number;
    perPage?: number;
}

export interface UpdateClusterRequest {
    clusterId: string;
    treeClusterUpdateRequest: TreeClusterUpdateRequest;
}

/**
 * 
 */
export class TreeClustersApi extends runtime.BaseAPI {

    /**
     * Creates a new tree cluster with the given properties and returns the created resource.
     * Create a tree cluster
     */
    async createClusterRaw(requestParameters: CreateClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeClusterResponse>> {
        if (requestParameters['treeClusterCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'treeClusterCreateRequest',
                'Required parameter "treeClusterCreateRequest" was null or undefined when calling createCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/clusters`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TreeClusterCreateRequestToJSON(requestParameters['treeClusterCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeClusterResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new tree cluster with the given properties and returns the created resource.
     * Create a tree cluster
     */
    async createCluster(requestParameters: CreateClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeClusterResponse> {
        const response = await this.createClusterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a tree cluster identified by its ID.
     * Delete a tree cluster
     */
    async deleteClusterRaw(requestParameters: DeleteClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling deleteCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/{cluster_id}`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a tree cluster identified by its ID.
     * Delete a tree cluster
     */
    async deleteCluster(requestParameters: DeleteClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteClusterRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a single tree cluster by its unique identifier, including fully resolved tree objects.
     * Get a tree cluster
     */
    async getClusterRaw(requestParameters: GetClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeClusterResponse>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling getCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/{cluster_id}`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeClusterResponseFromJSON(jsonValue));
    }

    /**
     * Returns a single tree cluster by its unique identifier, including fully resolved tree objects.
     * Get a tree cluster
     */
    async getCluster(requestParameters: GetClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeClusterResponse> {
        const response = await this.getClusterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns lightweight markers (id, name, lat, lng, status, tree_count) for all non-archived clusters with a centroid. Not paginated.
     * List cluster markers
     */
    async listClusterMarkersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterMarkerListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters/markers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterMarkerListResponseFromJSON(jsonValue));
    }

    /**
     * Returns lightweight markers (id, name, lat, lng, status, tree_count) for all non-archived clusters with a centroid. Not paginated.
     * List cluster markers
     */
    async listClusterMarkers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterMarkerListResponse> {
        const response = await this.listClusterMarkersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Returns a paginated list of all tree clusters with a compact representation including region info.
     * List all tree clusters
     */
    async listClustersRaw(requestParameters: ListClustersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResponseTreeClusterInListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/clusters`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResponseTreeClusterInListResponseFromJSON(jsonValue));
    }

    /**
     * Returns a paginated list of all tree clusters with a compact representation including region info.
     * List all tree clusters
     */
    async listClusters(requestParameters: ListClustersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResponseTreeClusterInListResponse> {
        const response = await this.listClustersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates an existing tree cluster identified by its ID and returns the updated resource.
     * Update a tree cluster
     */
    async updateClusterRaw(requestParameters: UpdateClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TreeClusterResponse>> {
        if (requestParameters['clusterId'] == null) {
            throw new runtime.RequiredError(
                'clusterId',
                'Required parameter "clusterId" was null or undefined when calling updateCluster().'
            );
        }

        if (requestParameters['treeClusterUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'treeClusterUpdateRequest',
                'Required parameter "treeClusterUpdateRequest" was null or undefined when calling updateCluster().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/clusters/{cluster_id}`;
        urlPath = urlPath.replace(`{${"cluster_id"}}`, encodeURIComponent(String(requestParameters['clusterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TreeClusterUpdateRequestToJSON(requestParameters['treeClusterUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TreeClusterResponseFromJSON(jsonValue));
    }

    /**
     * Updates an existing tree cluster identified by its ID and returns the updated resource.
     * Update a tree cluster
     */
    async updateCluster(requestParameters: UpdateClusterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TreeClusterResponse> {
        const response = await this.updateClusterRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
