/* tslint:disable */
/* eslint-disable */
/**
 * Green Ecolution Management API
 * This is the API for the Green Ecolution Management System.
 *
 * The version of the OpenAPI document: v0.1.1-1237e5c-stage
 * Contact: info@green-ecolution.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPError,
  Vehicle,
  VehicleCreate,
  VehicleList,
  VehicleUpdate,
} from '../models/index';
import {
    HTTPErrorFromJSON,
    HTTPErrorToJSON,
    VehicleFromJSON,
    VehicleToJSON,
    VehicleCreateFromJSON,
    VehicleCreateToJSON,
    VehicleListFromJSON,
    VehicleListToJSON,
    VehicleUpdateFromJSON,
    VehicleUpdateToJSON,
} from '../models/index';

export interface ArchiveVehicleRequest {
    id: number;
}

export interface CreateVehicleRequest {
    body: VehicleCreate;
}

export interface DeleteVehicleRequest {
    id: number;
}

export interface GetAllVehiclesRequest {
    page?: number;
    limit?: number;
    type?: string;
    provider?: string;
    archived?: boolean;
}

export interface GetVehicleByIdRequest {
    id: number;
}

export interface GetVehicleByPlateRequest {
    plate: string;
}

export interface UpdateVehicleRequest {
    id: string;
    body: VehicleUpdate;
}

/**
 * 
 */
export class VehicleApi extends runtime.BaseAPI {

    /**
     * Archive vehicle
     * Archive vehicle
     */
    async archiveVehicleRaw(requestParameters: ArchiveVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling archiveVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/vehicle/archive/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Archive vehicle
     * Archive vehicle
     */
    async archiveVehicle(requestParameters: ArchiveVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.archiveVehicleRaw(requestParameters, initOverrides);
    }

    /**
     * Create vehicle
     * Create vehicle
     */
    async createVehicleRaw(requestParameters: CreateVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling createVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/vehicle`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VehicleCreateToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Create vehicle
     * Create vehicle
     */
    async createVehicle(requestParameters: CreateVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.createVehicleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete vehicle
     * Delete vehicle
     */
    async deleteVehicleRaw(requestParameters: DeleteVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/vehicle/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete vehicle
     * Delete vehicle
     */
    async deleteVehicle(requestParameters: DeleteVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteVehicleRaw(requestParameters, initOverrides);
    }

    /**
     * Get all vehicles
     * Get all vehicles
     */
    async getAllVehiclesRaw(requestParameters: GetAllVehiclesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VehicleList>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['provider'] != null) {
            queryParameters['provider'] = requestParameters['provider'];
        }

        if (requestParameters['archived'] != null) {
            queryParameters['archived'] = requestParameters['archived'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/vehicle`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleListFromJSON(jsonValue));
    }

    /**
     * Get all vehicles
     * Get all vehicles
     */
    async getAllVehicles(requestParameters: GetAllVehiclesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VehicleList> {
        const response = await this.getAllVehiclesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get archived vehicle
     * Get archived vehicle
     */
    async getArchiveVehicleRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Vehicle>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/vehicle/archive`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VehicleFromJSON));
    }

    /**
     * Get archived vehicle
     * Get archived vehicle
     */
    async getArchiveVehicle(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Vehicle>> {
        const response = await this.getArchiveVehicleRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get vehicle by ID
     * Get vehicle by ID
     */
    async getVehicleByIdRaw(requestParameters: GetVehicleByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVehicleById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/vehicle/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Get vehicle by ID
     * Get vehicle by ID
     */
    async getVehicleById(requestParameters: GetVehicleByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.getVehicleByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get vehicle by plate
     * Get vehicle by plate
     */
    async getVehicleByPlateRaw(requestParameters: GetVehicleByPlateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters['plate'] == null) {
            throw new runtime.RequiredError(
                'plate',
                'Required parameter "plate" was null or undefined when calling getVehicleByPlate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/vehicle/plate/{plate}`;
        urlPath = urlPath.replace(`{${"plate"}}`, encodeURIComponent(String(requestParameters['plate'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Get vehicle by plate
     * Get vehicle by plate
     */
    async getVehicleByPlate(requestParameters: GetVehicleByPlateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.getVehicleByPlateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update vehicle
     * Update vehicle
     */
    async updateVehicleRaw(requestParameters: UpdateVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Vehicle>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateVehicle().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateVehicle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("Keycloak", []);
        }


        let urlPath = `/v1/vehicle/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: VehicleUpdateToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VehicleFromJSON(jsonValue));
    }

    /**
     * Update vehicle
     * Update vehicle
     */
    async updateVehicle(requestParameters: UpdateVehicleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Vehicle> {
        const response = await this.updateVehicleRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
