// Code generated by mockery v2.52.2. DO NOT EDIT.

package storagemock

import (
	context "context"

	shared "github.com/green-ecolution/green-ecolution/backend/internal/domain/shared"
	watering "github.com/green-ecolution/green-ecolution/backend/internal/domain/watering"
	mock "github.com/stretchr/testify/mock"
)

// MockWateringPlanRepository is an autogenerated mock type for the WateringPlanRepository type
type MockWateringPlanRepository struct {
	mock.Mock
}

type MockWateringPlanRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWateringPlanRepository) EXPECT() *MockWateringPlanRepository_Expecter {
	return &MockWateringPlanRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entity
func (_m *MockWateringPlanRepository) Create(ctx context.Context, entity *watering.WateringPlan) (*watering.WateringPlan, error) {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *watering.WateringPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *watering.WateringPlan) (*watering.WateringPlan, error)); ok {
		return rf(ctx, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *watering.WateringPlan) *watering.WateringPlan); ok {
		r0 = rf(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*watering.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *watering.WateringPlan) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWateringPlanRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *watering.WateringPlan
func (_e *MockWateringPlanRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockWateringPlanRepository_Create_Call {
	return &MockWateringPlanRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockWateringPlanRepository_Create_Call) Run(run func(ctx context.Context, entity *watering.WateringPlan)) *MockWateringPlanRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*watering.WateringPlan))
	})
	return _c
}

func (_c *MockWateringPlanRepository_Create_Call) Return(_a0 *watering.WateringPlan, _a1 error) *MockWateringPlanRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_Create_Call) RunAndReturn(run func(context.Context, *watering.WateringPlan) (*watering.WateringPlan, error)) *MockWateringPlanRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockWateringPlanRepository) Delete(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWateringPlanRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWateringPlanRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWateringPlanRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockWateringPlanRepository_Delete_Call {
	return &MockWateringPlanRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockWateringPlanRepository_Delete_Call) Run(run func(ctx context.Context, id int32)) *MockWateringPlanRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWateringPlanRepository_Delete_Call) Return(_a0 error) *MockWateringPlanRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWateringPlanRepository_Delete_Call) RunAndReturn(run func(context.Context, int32) error) *MockWateringPlanRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, query
func (_m *MockWateringPlanRepository) GetAll(ctx context.Context, query shared.Query) ([]*watering.WateringPlan, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*watering.WateringPlan
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Query) ([]*watering.WateringPlan, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.Query) []*watering.WateringPlan); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*watering.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.Query) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, shared.Query) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWateringPlanRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockWateringPlanRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - query shared.Query
func (_e *MockWateringPlanRepository_Expecter) GetAll(ctx interface{}, query interface{}) *MockWateringPlanRepository_GetAll_Call {
	return &MockWateringPlanRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, query)}
}

func (_c *MockWateringPlanRepository_GetAll_Call) Run(run func(ctx context.Context, query shared.Query)) *MockWateringPlanRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Query))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetAll_Call) Return(_a0 []*watering.WateringPlan, _a1 int64, _a2 error) *MockWateringPlanRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockWateringPlanRepository_GetAll_Call) RunAndReturn(run func(context.Context, shared.Query) ([]*watering.WateringPlan, int64, error)) *MockWateringPlanRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockWateringPlanRepository) GetByID(ctx context.Context, id int32) (*watering.WateringPlan, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *watering.WateringPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*watering.WateringPlan, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *watering.WateringPlan); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*watering.WateringPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWateringPlanRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockWateringPlanRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockWateringPlanRepository_GetByID_Call {
	return &MockWateringPlanRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockWateringPlanRepository_GetByID_Call) Run(run func(ctx context.Context, id int32)) *MockWateringPlanRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetByID_Call) Return(_a0 *watering.WateringPlan, _a1 error) *MockWateringPlanRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetByID_Call) RunAndReturn(run func(context.Context, int32) (*watering.WateringPlan, error)) *MockWateringPlanRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCount provides a mock function with given fields: ctx, query
func (_m *MockWateringPlanRepository) GetCount(ctx context.Context, query shared.Query) (int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Query) (int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.Query) int64); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.Query) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWateringPlanRepository_GetCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCount'
type MockWateringPlanRepository_GetCount_Call struct {
	*mock.Call
}

// GetCount is a helper method to define mock.On call
//   - ctx context.Context
//   - query shared.Query
func (_e *MockWateringPlanRepository_Expecter) GetCount(ctx interface{}, query interface{}) *MockWateringPlanRepository_GetCount_Call {
	return &MockWateringPlanRepository_GetCount_Call{Call: _e.mock.On("GetCount", ctx, query)}
}

func (_c *MockWateringPlanRepository_GetCount_Call) Run(run func(ctx context.Context, query shared.Query)) *MockWateringPlanRepository_GetCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Query))
	})
	return _c
}

func (_c *MockWateringPlanRepository_GetCount_Call) Return(_a0 int64, _a1 error) *MockWateringPlanRepository_GetCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWateringPlanRepository_GetCount_Call) RunAndReturn(run func(context.Context, shared.Query) (int64, error)) *MockWateringPlanRepository_GetCount_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, entity
func (_m *MockWateringPlanRepository) Update(ctx context.Context, id int32, entity *watering.WateringPlan) error {
	ret := _m.Called(ctx, id, entity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, *watering.WateringPlan) error); ok {
		r0 = rf(ctx, id, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWateringPlanRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWateringPlanRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - entity *watering.WateringPlan
func (_e *MockWateringPlanRepository_Expecter) Update(ctx interface{}, id interface{}, entity interface{}) *MockWateringPlanRepository_Update_Call {
	return &MockWateringPlanRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, entity)}
}

func (_c *MockWateringPlanRepository_Update_Call) Run(run func(ctx context.Context, id int32, entity *watering.WateringPlan)) *MockWateringPlanRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(*watering.WateringPlan))
	})
	return _c
}

func (_c *MockWateringPlanRepository_Update_Call) Return(_a0 error) *MockWateringPlanRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWateringPlanRepository_Update_Call) RunAndReturn(run func(context.Context, int32, *watering.WateringPlan) error) *MockWateringPlanRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWateringPlanRepository creates a new instance of MockWateringPlanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWateringPlanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWateringPlanRepository {
	mock := &MockWateringPlanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
