// Code generated by mockery v2.52.2. DO NOT EDIT.

package storagemock

import (
	context "context"

	sensor "github.com/green-ecolution/green-ecolution/backend/internal/domain/sensor"
	shared "github.com/green-ecolution/green-ecolution/backend/internal/domain/shared"
	mock "github.com/stretchr/testify/mock"
)

// MockSensorRepository is an autogenerated mock type for the SensorRepository type
type MockSensorRepository struct {
	mock.Mock
}

type MockSensorRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSensorRepository) EXPECT() *MockSensorRepository_Expecter {
	return &MockSensorRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entity
func (_m *MockSensorRepository) Create(ctx context.Context, entity *sensor.Sensor) (*sensor.Sensor, error) {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *sensor.Sensor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sensor.Sensor) (*sensor.Sensor, error)); ok {
		return rf(ctx, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sensor.Sensor) *sensor.Sensor); ok {
		r0 = rf(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sensor.Sensor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sensor.Sensor) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSensorRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *sensor.Sensor
func (_e *MockSensorRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockSensorRepository_Create_Call {
	return &MockSensorRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockSensorRepository_Create_Call) Run(run func(ctx context.Context, entity *sensor.Sensor)) *MockSensorRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sensor.Sensor))
	})
	return _c
}

func (_c *MockSensorRepository_Create_Call) Return(_a0 *sensor.Sensor, _a1 error) *MockSensorRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorRepository_Create_Call) RunAndReturn(run func(context.Context, *sensor.Sensor) (*sensor.Sensor, error)) *MockSensorRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSensorRepository) Delete(ctx context.Context, id sensor.SensorID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSensorRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSensorRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id sensor.SensorID
func (_e *MockSensorRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockSensorRepository_Delete_Call {
	return &MockSensorRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSensorRepository_Delete_Call) Run(run func(ctx context.Context, id sensor.SensorID)) *MockSensorRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sensor.SensorID))
	})
	return _c
}

func (_c *MockSensorRepository_Delete_Call) Return(_a0 error) *MockSensorRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSensorRepository_Delete_Call) RunAndReturn(run func(context.Context, sensor.SensorID) error) *MockSensorRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, query
func (_m *MockSensorRepository) GetAll(ctx context.Context, query shared.Query) ([]*sensor.Sensor, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*sensor.Sensor
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Query) ([]*sensor.Sensor, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.Query) []*sensor.Sensor); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sensor.Sensor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.Query) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, shared.Query) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSensorRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockSensorRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - query shared.Query
func (_e *MockSensorRepository_Expecter) GetAll(ctx interface{}, query interface{}) *MockSensorRepository_GetAll_Call {
	return &MockSensorRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, query)}
}

func (_c *MockSensorRepository_GetAll_Call) Run(run func(ctx context.Context, query shared.Query)) *MockSensorRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Query))
	})
	return _c
}

func (_c *MockSensorRepository_GetAll_Call) Return(_a0 []*sensor.Sensor, _a1 int64, _a2 error) *MockSensorRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSensorRepository_GetAll_Call) RunAndReturn(run func(context.Context, shared.Query) ([]*sensor.Sensor, int64, error)) *MockSensorRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllDataByID provides a mock function with given fields: ctx, id
func (_m *MockSensorRepository) GetAllDataByID(ctx context.Context, id sensor.SensorID) ([]*sensor.SensorData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAllDataByID")
	}

	var r0 []*sensor.SensorData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID) ([]*sensor.SensorData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID) []*sensor.SensorData); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*sensor.SensorData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sensor.SensorID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorRepository_GetAllDataByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllDataByID'
type MockSensorRepository_GetAllDataByID_Call struct {
	*mock.Call
}

// GetAllDataByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id sensor.SensorID
func (_e *MockSensorRepository_Expecter) GetAllDataByID(ctx interface{}, id interface{}) *MockSensorRepository_GetAllDataByID_Call {
	return &MockSensorRepository_GetAllDataByID_Call{Call: _e.mock.On("GetAllDataByID", ctx, id)}
}

func (_c *MockSensorRepository_GetAllDataByID_Call) Run(run func(ctx context.Context, id sensor.SensorID)) *MockSensorRepository_GetAllDataByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sensor.SensorID))
	})
	return _c
}

func (_c *MockSensorRepository_GetAllDataByID_Call) Return(_a0 []*sensor.SensorData, _a1 error) *MockSensorRepository_GetAllDataByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorRepository_GetAllDataByID_Call) RunAndReturn(run func(context.Context, sensor.SensorID) ([]*sensor.SensorData, error)) *MockSensorRepository_GetAllDataByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockSensorRepository) GetByID(ctx context.Context, id sensor.SensorID) (*sensor.Sensor, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *sensor.Sensor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID) (*sensor.Sensor, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID) *sensor.Sensor); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sensor.Sensor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sensor.SensorID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSensorRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id sensor.SensorID
func (_e *MockSensorRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSensorRepository_GetByID_Call {
	return &MockSensorRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSensorRepository_GetByID_Call) Run(run func(ctx context.Context, id sensor.SensorID)) *MockSensorRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sensor.SensorID))
	})
	return _c
}

func (_c *MockSensorRepository_GetByID_Call) Return(_a0 *sensor.Sensor, _a1 error) *MockSensorRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorRepository_GetByID_Call) RunAndReturn(run func(context.Context, sensor.SensorID) (*sensor.Sensor, error)) *MockSensorRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCount provides a mock function with given fields: ctx, query
func (_m *MockSensorRepository) GetCount(ctx context.Context, query shared.Query) (int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Query) (int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.Query) int64); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.Query) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorRepository_GetCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCount'
type MockSensorRepository_GetCount_Call struct {
	*mock.Call
}

// GetCount is a helper method to define mock.On call
//   - ctx context.Context
//   - query shared.Query
func (_e *MockSensorRepository_Expecter) GetCount(ctx interface{}, query interface{}) *MockSensorRepository_GetCount_Call {
	return &MockSensorRepository_GetCount_Call{Call: _e.mock.On("GetCount", ctx, query)}
}

func (_c *MockSensorRepository_GetCount_Call) Run(run func(ctx context.Context, query shared.Query)) *MockSensorRepository_GetCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Query))
	})
	return _c
}

func (_c *MockSensorRepository_GetCount_Call) Return(_a0 int64, _a1 error) *MockSensorRepository_GetCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorRepository_GetCount_Call) RunAndReturn(run func(context.Context, shared.Query) (int64, error)) *MockSensorRepository_GetCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestSensorDataBySensorID provides a mock function with given fields: ctx, id
func (_m *MockSensorRepository) GetLatestSensorDataBySensorID(ctx context.Context, id sensor.SensorID) (*sensor.SensorData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestSensorDataBySensorID")
	}

	var r0 *sensor.SensorData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID) (*sensor.SensorData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID) *sensor.SensorData); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sensor.SensorData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sensor.SensorID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorRepository_GetLatestSensorDataBySensorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestSensorDataBySensorID'
type MockSensorRepository_GetLatestSensorDataBySensorID_Call struct {
	*mock.Call
}

// GetLatestSensorDataBySensorID is a helper method to define mock.On call
//   - ctx context.Context
//   - id sensor.SensorID
func (_e *MockSensorRepository_Expecter) GetLatestSensorDataBySensorID(ctx interface{}, id interface{}) *MockSensorRepository_GetLatestSensorDataBySensorID_Call {
	return &MockSensorRepository_GetLatestSensorDataBySensorID_Call{Call: _e.mock.On("GetLatestSensorDataBySensorID", ctx, id)}
}

func (_c *MockSensorRepository_GetLatestSensorDataBySensorID_Call) Run(run func(ctx context.Context, id sensor.SensorID)) *MockSensorRepository_GetLatestSensorDataBySensorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sensor.SensorID))
	})
	return _c
}

func (_c *MockSensorRepository_GetLatestSensorDataBySensorID_Call) Return(_a0 *sensor.SensorData, _a1 error) *MockSensorRepository_GetLatestSensorDataBySensorID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorRepository_GetLatestSensorDataBySensorID_Call) RunAndReturn(run func(context.Context, sensor.SensorID) (*sensor.SensorData, error)) *MockSensorRepository_GetLatestSensorDataBySensorID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertSensorData provides a mock function with given fields: ctx, data, id
func (_m *MockSensorRepository) InsertSensorData(ctx context.Context, data *sensor.SensorData, id sensor.SensorID) error {
	ret := _m.Called(ctx, data, id)

	if len(ret) == 0 {
		panic("no return value specified for InsertSensorData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sensor.SensorData, sensor.SensorID) error); ok {
		r0 = rf(ctx, data, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSensorRepository_InsertSensorData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertSensorData'
type MockSensorRepository_InsertSensorData_Call struct {
	*mock.Call
}

// InsertSensorData is a helper method to define mock.On call
//   - ctx context.Context
//   - data *sensor.SensorData
//   - id sensor.SensorID
func (_e *MockSensorRepository_Expecter) InsertSensorData(ctx interface{}, data interface{}, id interface{}) *MockSensorRepository_InsertSensorData_Call {
	return &MockSensorRepository_InsertSensorData_Call{Call: _e.mock.On("InsertSensorData", ctx, data, id)}
}

func (_c *MockSensorRepository_InsertSensorData_Call) Run(run func(ctx context.Context, data *sensor.SensorData, id sensor.SensorID)) *MockSensorRepository_InsertSensorData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sensor.SensorData), args[2].(sensor.SensorID))
	})
	return _c
}

func (_c *MockSensorRepository_InsertSensorData_Call) Return(_a0 error) *MockSensorRepository_InsertSensorData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSensorRepository_InsertSensorData_Call) RunAndReturn(run func(context.Context, *sensor.SensorData, sensor.SensorID) error) *MockSensorRepository_InsertSensorData_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, entity
func (_m *MockSensorRepository) Update(ctx context.Context, id sensor.SensorID, entity *sensor.Sensor) (*sensor.Sensor, error) {
	ret := _m.Called(ctx, id, entity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *sensor.Sensor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID, *sensor.Sensor) (*sensor.Sensor, error)); ok {
		return rf(ctx, id, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID, *sensor.Sensor) *sensor.Sensor); ok {
		r0 = rf(ctx, id, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sensor.Sensor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, sensor.SensorID, *sensor.Sensor) error); ok {
		r1 = rf(ctx, id, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSensorRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockSensorRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id sensor.SensorID
//   - entity *sensor.Sensor
func (_e *MockSensorRepository_Expecter) Update(ctx interface{}, id interface{}, entity interface{}) *MockSensorRepository_Update_Call {
	return &MockSensorRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, entity)}
}

func (_c *MockSensorRepository_Update_Call) Run(run func(ctx context.Context, id sensor.SensorID, entity *sensor.Sensor)) *MockSensorRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sensor.SensorID), args[2].(*sensor.Sensor))
	})
	return _c
}

func (_c *MockSensorRepository_Update_Call) Return(_a0 *sensor.Sensor, _a1 error) *MockSensorRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSensorRepository_Update_Call) RunAndReturn(run func(context.Context, sensor.SensorID, *sensor.Sensor) (*sensor.Sensor, error)) *MockSensorRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSensorRepository creates a new instance of MockSensorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSensorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSensorRepository {
	mock := &MockSensorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
