// Code generated by mockery v2.52.2. DO NOT EDIT.

package storagemock

import (
	context "context"

	sensor "github.com/green-ecolution/green-ecolution/backend/internal/domain/sensor"
	shared "github.com/green-ecolution/green-ecolution/backend/internal/domain/shared"
	mock "github.com/stretchr/testify/mock"

	tree "github.com/green-ecolution/green-ecolution/backend/internal/domain/tree"
)

// MockTreeRepository is an autogenerated mock type for the TreeRepository type
type MockTreeRepository struct {
	mock.Mock
}

type MockTreeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTreeRepository) EXPECT() *MockTreeRepository_Expecter {
	return &MockTreeRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, entity
func (_m *MockTreeRepository) Create(ctx context.Context, entity *tree.Tree) (*tree.Tree, error) {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *tree.Tree
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *tree.Tree) (*tree.Tree, error)); ok {
		return rf(ctx, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *tree.Tree) *tree.Tree); ok {
		r0 = rf(ctx, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tree.Tree)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *tree.Tree) error); ok {
		r1 = rf(ctx, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTreeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTreeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *tree.Tree
func (_e *MockTreeRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockTreeRepository_Create_Call {
	return &MockTreeRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockTreeRepository_Create_Call) Run(run func(ctx context.Context, entity *tree.Tree)) *MockTreeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tree.Tree))
	})
	return _c
}

func (_c *MockTreeRepository_Create_Call) Return(_a0 *tree.Tree, _a1 error) *MockTreeRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTreeRepository_Create_Call) RunAndReturn(run func(context.Context, *tree.Tree) (*tree.Tree, error)) *MockTreeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTreeRepository) Delete(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTreeRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTreeRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockTreeRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTreeRepository_Delete_Call {
	return &MockTreeRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTreeRepository_Delete_Call) Run(run func(ctx context.Context, id int32)) *MockTreeRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockTreeRepository_Delete_Call) Return(_a0 error) *MockTreeRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTreeRepository_Delete_Call) RunAndReturn(run func(context.Context, int32) error) *MockTreeRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindNearestTrees provides a mock function with given fields: ctx, coord, radiusMeters, limit
func (_m *MockTreeRepository) FindNearestTrees(ctx context.Context, coord shared.Coordinate, radiusMeters float64, limit int32) ([]*tree.TreeWithDistance, error) {
	ret := _m.Called(ctx, coord, radiusMeters, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindNearestTrees")
	}

	var r0 []*tree.TreeWithDistance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Coordinate, float64, int32) ([]*tree.TreeWithDistance, error)); ok {
		return rf(ctx, coord, radiusMeters, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.Coordinate, float64, int32) []*tree.TreeWithDistance); ok {
		r0 = rf(ctx, coord, radiusMeters, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tree.TreeWithDistance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.Coordinate, float64, int32) error); ok {
		r1 = rf(ctx, coord, radiusMeters, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTreeRepository_FindNearestTrees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNearestTrees'
type MockTreeRepository_FindNearestTrees_Call struct {
	*mock.Call
}

// FindNearestTrees is a helper method to define mock.On call
//   - ctx context.Context
//   - coord shared.Coordinate
//   - radiusMeters float64
//   - limit int32
func (_e *MockTreeRepository_Expecter) FindNearestTrees(ctx interface{}, coord interface{}, radiusMeters interface{}, limit interface{}) *MockTreeRepository_FindNearestTrees_Call {
	return &MockTreeRepository_FindNearestTrees_Call{Call: _e.mock.On("FindNearestTrees", ctx, coord, radiusMeters, limit)}
}

func (_c *MockTreeRepository_FindNearestTrees_Call) Run(run func(ctx context.Context, coord shared.Coordinate, radiusMeters float64, limit int32)) *MockTreeRepository_FindNearestTrees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Coordinate), args[2].(float64), args[3].(int32))
	})
	return _c
}

func (_c *MockTreeRepository_FindNearestTrees_Call) Return(_a0 []*tree.TreeWithDistance, _a1 error) *MockTreeRepository_FindNearestTrees_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTreeRepository_FindNearestTrees_Call) RunAndReturn(run func(context.Context, shared.Coordinate, float64, int32) ([]*tree.TreeWithDistance, error)) *MockTreeRepository_FindNearestTrees_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, query
func (_m *MockTreeRepository) GetAll(ctx context.Context, query tree.TreeQuery) ([]*tree.Tree, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*tree.Tree
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, tree.TreeQuery) ([]*tree.Tree, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tree.TreeQuery) []*tree.Tree); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tree.Tree)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, tree.TreeQuery) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, tree.TreeQuery) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTreeRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTreeRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - query tree.TreeQuery
func (_e *MockTreeRepository_Expecter) GetAll(ctx interface{}, query interface{}) *MockTreeRepository_GetAll_Call {
	return &MockTreeRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, query)}
}

func (_c *MockTreeRepository_GetAll_Call) Run(run func(ctx context.Context, query tree.TreeQuery)) *MockTreeRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(tree.TreeQuery))
	})
	return _c
}

func (_c *MockTreeRepository_GetAll_Call) Return(_a0 []*tree.Tree, _a1 int64, _a2 error) *MockTreeRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTreeRepository_GetAll_Call) RunAndReturn(run func(context.Context, tree.TreeQuery) ([]*tree.Tree, int64, error)) *MockTreeRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTreeRepository) GetByID(ctx context.Context, id int32) (*tree.Tree, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *tree.Tree
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*tree.Tree, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *tree.Tree); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tree.Tree)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTreeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTreeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockTreeRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTreeRepository_GetByID_Call {
	return &MockTreeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTreeRepository_GetByID_Call) Run(run func(ctx context.Context, id int32)) *MockTreeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockTreeRepository_GetByID_Call) Return(_a0 *tree.Tree, _a1 error) *MockTreeRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTreeRepository_GetByID_Call) RunAndReturn(run func(context.Context, int32) (*tree.Tree, error)) *MockTreeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCount provides a mock function with given fields: ctx, query
func (_m *MockTreeRepository) GetCount(ctx context.Context, query tree.TreeQuery) (int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, tree.TreeQuery) (int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, tree.TreeQuery) int64); ok {
		r0 = rf(ctx, query)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, tree.TreeQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTreeRepository_GetCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCount'
type MockTreeRepository_GetCount_Call struct {
	*mock.Call
}

// GetCount is a helper method to define mock.On call
//   - ctx context.Context
//   - query tree.TreeQuery
func (_e *MockTreeRepository_Expecter) GetCount(ctx interface{}, query interface{}) *MockTreeRepository_GetCount_Call {
	return &MockTreeRepository_GetCount_Call{Call: _e.mock.On("GetCount", ctx, query)}
}

func (_c *MockTreeRepository_GetCount_Call) Run(run func(ctx context.Context, query tree.TreeQuery)) *MockTreeRepository_GetCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(tree.TreeQuery))
	})
	return _c
}

func (_c *MockTreeRepository_GetCount_Call) Return(_a0 int64, _a1 error) *MockTreeRepository_GetCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTreeRepository_GetCount_Call) RunAndReturn(run func(context.Context, tree.TreeQuery) (int64, error)) *MockTreeRepository_GetCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistinctPlantingYears provides a mock function with given fields: ctx
func (_m *MockTreeRepository) GetDistinctPlantingYears(ctx context.Context) ([]int32, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctPlantingYears")
	}

	var r0 []int32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int32, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int32); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTreeRepository_GetDistinctPlantingYears_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistinctPlantingYears'
type MockTreeRepository_GetDistinctPlantingYears_Call struct {
	*mock.Call
}

// GetDistinctPlantingYears is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTreeRepository_Expecter) GetDistinctPlantingYears(ctx interface{}) *MockTreeRepository_GetDistinctPlantingYears_Call {
	return &MockTreeRepository_GetDistinctPlantingYears_Call{Call: _e.mock.On("GetDistinctPlantingYears", ctx)}
}

func (_c *MockTreeRepository_GetDistinctPlantingYears_Call) Run(run func(ctx context.Context)) *MockTreeRepository_GetDistinctPlantingYears_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTreeRepository_GetDistinctPlantingYears_Call) Return(_a0 []int32, _a1 error) *MockTreeRepository_GetDistinctPlantingYears_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTreeRepository_GetDistinctPlantingYears_Call) RunAndReturn(run func(context.Context) ([]int32, error)) *MockTreeRepository_GetDistinctPlantingYears_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkSensorID provides a mock function with given fields: ctx, sensorID
func (_m *MockTreeRepository) UnlinkSensorID(ctx context.Context, sensorID sensor.SensorID) error {
	ret := _m.Called(ctx, sensorID)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkSensorID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, sensor.SensorID) error); ok {
		r0 = rf(ctx, sensorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTreeRepository_UnlinkSensorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkSensorID'
type MockTreeRepository_UnlinkSensorID_Call struct {
	*mock.Call
}

// UnlinkSensorID is a helper method to define mock.On call
//   - ctx context.Context
//   - sensorID sensor.SensorID
func (_e *MockTreeRepository_Expecter) UnlinkSensorID(ctx interface{}, sensorID interface{}) *MockTreeRepository_UnlinkSensorID_Call {
	return &MockTreeRepository_UnlinkSensorID_Call{Call: _e.mock.On("UnlinkSensorID", ctx, sensorID)}
}

func (_c *MockTreeRepository_UnlinkSensorID_Call) Run(run func(ctx context.Context, sensorID sensor.SensorID)) *MockTreeRepository_UnlinkSensorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(sensor.SensorID))
	})
	return _c
}

func (_c *MockTreeRepository_UnlinkSensorID_Call) Return(_a0 error) *MockTreeRepository_UnlinkSensorID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTreeRepository_UnlinkSensorID_Call) RunAndReturn(run func(context.Context, sensor.SensorID) error) *MockTreeRepository_UnlinkSensorID_Call {
	_c.Call.Return(run)
	return _c
}

// UnlinkTreeClusterID provides a mock function with given fields: ctx, treeClusterID
func (_m *MockTreeRepository) UnlinkTreeClusterID(ctx context.Context, treeClusterID int32) error {
	ret := _m.Called(ctx, treeClusterID)

	if len(ret) == 0 {
		panic("no return value specified for UnlinkTreeClusterID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, treeClusterID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTreeRepository_UnlinkTreeClusterID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlinkTreeClusterID'
type MockTreeRepository_UnlinkTreeClusterID_Call struct {
	*mock.Call
}

// UnlinkTreeClusterID is a helper method to define mock.On call
//   - ctx context.Context
//   - treeClusterID int32
func (_e *MockTreeRepository_Expecter) UnlinkTreeClusterID(ctx interface{}, treeClusterID interface{}) *MockTreeRepository_UnlinkTreeClusterID_Call {
	return &MockTreeRepository_UnlinkTreeClusterID_Call{Call: _e.mock.On("UnlinkTreeClusterID", ctx, treeClusterID)}
}

func (_c *MockTreeRepository_UnlinkTreeClusterID_Call) Run(run func(ctx context.Context, treeClusterID int32)) *MockTreeRepository_UnlinkTreeClusterID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *MockTreeRepository_UnlinkTreeClusterID_Call) Return(_a0 error) *MockTreeRepository_UnlinkTreeClusterID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTreeRepository_UnlinkTreeClusterID_Call) RunAndReturn(run func(context.Context, int32) error) *MockTreeRepository_UnlinkTreeClusterID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, entity
func (_m *MockTreeRepository) Update(ctx context.Context, id int32, entity *tree.Tree) (*tree.Tree, error) {
	ret := _m.Called(ctx, id, entity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *tree.Tree
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, *tree.Tree) (*tree.Tree, error)); ok {
		return rf(ctx, id, entity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, *tree.Tree) *tree.Tree); ok {
		r0 = rf(ctx, id, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tree.Tree)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, *tree.Tree) error); ok {
		r1 = rf(ctx, id, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTreeRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTreeRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
//   - entity *tree.Tree
func (_e *MockTreeRepository_Expecter) Update(ctx interface{}, id interface{}, entity interface{}) *MockTreeRepository_Update_Call {
	return &MockTreeRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, entity)}
}

func (_c *MockTreeRepository_Update_Call) Run(run func(ctx context.Context, id int32, entity *tree.Tree)) *MockTreeRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(*tree.Tree))
	})
	return _c
}

func (_c *MockTreeRepository_Update_Call) Return(_a0 *tree.Tree, _a1 error) *MockTreeRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTreeRepository_Update_Call) RunAndReturn(run func(context.Context, int32, *tree.Tree) (*tree.Tree, error)) *MockTreeRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTreeRepository creates a new instance of MockTreeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTreeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTreeRepository {
	mock := &MockTreeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
