// Code generated by mockery v2.52.2. DO NOT EDIT.

package storagemock

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	routing "github.com/green-ecolution/green-ecolution/backend/internal/domain/routing"

	shared "github.com/green-ecolution/green-ecolution/backend/internal/domain/shared"
)

// MockRoutingRepository is an autogenerated mock type for the RoutingRepository type
type MockRoutingRepository struct {
	mock.Mock
}

type MockRoutingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoutingRepository) EXPECT() *MockRoutingRepository_Expecter {
	return &MockRoutingRepository_Expecter{mock: &_m.Mock}
}

// GenerateRawGpxRoute provides a mock function with given fields: ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates
func (_m *MockRoutingRepository) GenerateRawGpxRoute(ctx context.Context, vehicleHeight float64, vehicleWidth float64, vehicleLength float64, vehicleWeight float64, clusterCoordinates []shared.Coordinate) (io.ReadCloser, error) {
	ret := _m.Called(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRawGpxRoute")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, []shared.Coordinate) (io.ReadCloser, error)); ok {
		return rf(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, []shared.Coordinate) io.ReadCloser); ok {
		r0 = rf(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, float64, float64, []shared.Coordinate) error); ok {
		r1 = rf(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoutingRepository_GenerateRawGpxRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRawGpxRoute'
type MockRoutingRepository_GenerateRawGpxRoute_Call struct {
	*mock.Call
}

// GenerateRawGpxRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - vehicleHeight float64
//   - vehicleWidth float64
//   - vehicleLength float64
//   - vehicleWeight float64
//   - clusterCoordinates []shared.Coordinate
func (_e *MockRoutingRepository_Expecter) GenerateRawGpxRoute(ctx interface{}, vehicleHeight interface{}, vehicleWidth interface{}, vehicleLength interface{}, vehicleWeight interface{}, clusterCoordinates interface{}) *MockRoutingRepository_GenerateRawGpxRoute_Call {
	return &MockRoutingRepository_GenerateRawGpxRoute_Call{Call: _e.mock.On("GenerateRawGpxRoute", ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)}
}

func (_c *MockRoutingRepository_GenerateRawGpxRoute_Call) Run(run func(ctx context.Context, vehicleHeight float64, vehicleWidth float64, vehicleLength float64, vehicleWeight float64, clusterCoordinates []shared.Coordinate)) *MockRoutingRepository_GenerateRawGpxRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64), args[3].(float64), args[4].(float64), args[5].([]shared.Coordinate))
	})
	return _c
}

func (_c *MockRoutingRepository_GenerateRawGpxRoute_Call) Return(_a0 io.ReadCloser, _a1 error) *MockRoutingRepository_GenerateRawGpxRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoutingRepository_GenerateRawGpxRoute_Call) RunAndReturn(run func(context.Context, float64, float64, float64, float64, []shared.Coordinate) (io.ReadCloser, error)) *MockRoutingRepository_GenerateRawGpxRoute_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRoute provides a mock function with given fields: ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates
func (_m *MockRoutingRepository) GenerateRoute(ctx context.Context, vehicleHeight float64, vehicleWidth float64, vehicleLength float64, vehicleWeight float64, clusterCoordinates []shared.Coordinate) (*routing.GeoJSON, error) {
	ret := _m.Called(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRoute")
	}

	var r0 *routing.GeoJSON
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, []shared.Coordinate) (*routing.GeoJSON, error)); ok {
		return rf(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, []shared.Coordinate) *routing.GeoJSON); ok {
		r0 = rf(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.GeoJSON)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, float64, float64, []shared.Coordinate) error); ok {
		r1 = rf(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoutingRepository_GenerateRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRoute'
type MockRoutingRepository_GenerateRoute_Call struct {
	*mock.Call
}

// GenerateRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - vehicleHeight float64
//   - vehicleWidth float64
//   - vehicleLength float64
//   - vehicleWeight float64
//   - clusterCoordinates []shared.Coordinate
func (_e *MockRoutingRepository_Expecter) GenerateRoute(ctx interface{}, vehicleHeight interface{}, vehicleWidth interface{}, vehicleLength interface{}, vehicleWeight interface{}, clusterCoordinates interface{}) *MockRoutingRepository_GenerateRoute_Call {
	return &MockRoutingRepository_GenerateRoute_Call{Call: _e.mock.On("GenerateRoute", ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, clusterCoordinates)}
}

func (_c *MockRoutingRepository_GenerateRoute_Call) Run(run func(ctx context.Context, vehicleHeight float64, vehicleWidth float64, vehicleLength float64, vehicleWeight float64, clusterCoordinates []shared.Coordinate)) *MockRoutingRepository_GenerateRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64), args[3].(float64), args[4].(float64), args[5].([]shared.Coordinate))
	})
	return _c
}

func (_c *MockRoutingRepository_GenerateRoute_Call) Return(_a0 *routing.GeoJSON, _a1 error) *MockRoutingRepository_GenerateRoute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoutingRepository_GenerateRoute_Call) RunAndReturn(run func(context.Context, float64, float64, float64, float64, []shared.Coordinate) (*routing.GeoJSON, error)) *MockRoutingRepository_GenerateRoute_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRouteInformation provides a mock function with given fields: ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, waterCapacity, clusterCoordinates, treeCounts
func (_m *MockRoutingRepository) GenerateRouteInformation(ctx context.Context, vehicleHeight float64, vehicleWidth float64, vehicleLength float64, vehicleWeight float64, waterCapacity shared.WaterCapacity, clusterCoordinates []shared.Coordinate, treeCounts []int) (*routing.RouteMetadata, error) {
	ret := _m.Called(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, waterCapacity, clusterCoordinates, treeCounts)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRouteInformation")
	}

	var r0 *routing.RouteMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, shared.WaterCapacity, []shared.Coordinate, []int) (*routing.RouteMetadata, error)); ok {
		return rf(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, waterCapacity, clusterCoordinates, treeCounts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64, float64, float64, float64, shared.WaterCapacity, []shared.Coordinate, []int) *routing.RouteMetadata); ok {
		r0 = rf(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, waterCapacity, clusterCoordinates, treeCounts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*routing.RouteMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64, float64, float64, float64, shared.WaterCapacity, []shared.Coordinate, []int) error); ok {
		r1 = rf(ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, waterCapacity, clusterCoordinates, treeCounts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoutingRepository_GenerateRouteInformation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRouteInformation'
type MockRoutingRepository_GenerateRouteInformation_Call struct {
	*mock.Call
}

// GenerateRouteInformation is a helper method to define mock.On call
//   - ctx context.Context
//   - vehicleHeight float64
//   - vehicleWidth float64
//   - vehicleLength float64
//   - vehicleWeight float64
//   - waterCapacity shared.WaterCapacity
//   - clusterCoordinates []shared.Coordinate
//   - treeCounts []int
func (_e *MockRoutingRepository_Expecter) GenerateRouteInformation(ctx interface{}, vehicleHeight interface{}, vehicleWidth interface{}, vehicleLength interface{}, vehicleWeight interface{}, waterCapacity interface{}, clusterCoordinates interface{}, treeCounts interface{}) *MockRoutingRepository_GenerateRouteInformation_Call {
	return &MockRoutingRepository_GenerateRouteInformation_Call{Call: _e.mock.On("GenerateRouteInformation", ctx, vehicleHeight, vehicleWidth, vehicleLength, vehicleWeight, waterCapacity, clusterCoordinates, treeCounts)}
}

func (_c *MockRoutingRepository_GenerateRouteInformation_Call) Run(run func(ctx context.Context, vehicleHeight float64, vehicleWidth float64, vehicleLength float64, vehicleWeight float64, waterCapacity shared.WaterCapacity, clusterCoordinates []shared.Coordinate, treeCounts []int)) *MockRoutingRepository_GenerateRouteInformation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64), args[2].(float64), args[3].(float64), args[4].(float64), args[5].(shared.WaterCapacity), args[6].([]shared.Coordinate), args[7].([]int))
	})
	return _c
}

func (_c *MockRoutingRepository_GenerateRouteInformation_Call) Return(_a0 *routing.RouteMetadata, _a1 error) *MockRoutingRepository_GenerateRouteInformation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoutingRepository_GenerateRouteInformation_Call) RunAndReturn(run func(context.Context, float64, float64, float64, float64, shared.WaterCapacity, []shared.Coordinate, []int) (*routing.RouteMetadata, error)) *MockRoutingRepository_GenerateRouteInformation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoutingRepository creates a new instance of MockRoutingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoutingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoutingRepository {
	mock := &MockRoutingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
