// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	geos "github.com/twpayne/go-geos"
)

type DrivingLicense string

const (
	DrivingLicenseB  DrivingLicense = "B"
	DrivingLicenseBE DrivingLicense = "BE"
	DrivingLicenseC  DrivingLicense = "C"
	DrivingLicenseCE DrivingLicense = "CE"
)

func (e *DrivingLicense) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DrivingLicense(s)
	case string:
		*e = DrivingLicense(s)
	default:
		return fmt.Errorf("unsupported scan type for DrivingLicense: %T", src)
	}
	return nil
}

type NullDrivingLicense struct {
	DrivingLicense DrivingLicense
	Valid          bool // Valid is true if DrivingLicense is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDrivingLicense) Scan(value interface{}) error {
	if value == nil {
		ns.DrivingLicense, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DrivingLicense.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDrivingLicense) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DrivingLicense), nil
}

type SensorStatus string

const (
	SensorStatusOnline  SensorStatus = "online"
	SensorStatusOffline SensorStatus = "offline"
	SensorStatusUnknown SensorStatus = "unknown"
)

func (e *SensorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SensorStatus(s)
	case string:
		*e = SensorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SensorStatus: %T", src)
	}
	return nil
}

type NullSensorStatus struct {
	SensorStatus SensorStatus
	Valid        bool // Valid is true if SensorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSensorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SensorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SensorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSensorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SensorStatus), nil
}

type TreeSoilCondition string

const (
	TreeSoilConditionSchluffig TreeSoilCondition = "schluffig"
	TreeSoilConditionSandig    TreeSoilCondition = "sandig"
	TreeSoilConditionLehmig    TreeSoilCondition = "lehmig"
	TreeSoilConditionTonig     TreeSoilCondition = "tonig"
	TreeSoilConditionUnknown   TreeSoilCondition = "unknown"
)

func (e *TreeSoilCondition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TreeSoilCondition(s)
	case string:
		*e = TreeSoilCondition(s)
	default:
		return fmt.Errorf("unsupported scan type for TreeSoilCondition: %T", src)
	}
	return nil
}

type NullTreeSoilCondition struct {
	TreeSoilCondition TreeSoilCondition
	Valid             bool // Valid is true if TreeSoilCondition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTreeSoilCondition) Scan(value interface{}) error {
	if value == nil {
		ns.TreeSoilCondition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TreeSoilCondition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTreeSoilCondition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TreeSoilCondition), nil
}

type VehicleStatus string

const (
	VehicleStatusActive       VehicleStatus = "active"
	VehicleStatusAvailable    VehicleStatus = "available"
	VehicleStatusNotavailable VehicleStatus = "not available"
	VehicleStatusUnknown      VehicleStatus = "unknown"
)

func (e *VehicleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehicleStatus(s)
	case string:
		*e = VehicleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VehicleStatus: %T", src)
	}
	return nil
}

type NullVehicleStatus struct {
	VehicleStatus VehicleStatus
	Valid         bool // Valid is true if VehicleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehicleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VehicleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehicleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehicleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehicleStatus), nil
}

type VehicleType string

const (
	VehicleTypeTransporter VehicleType = "transporter"
	VehicleTypeTrailer     VehicleType = "trailer"
	VehicleTypeUnknown     VehicleType = "unknown"
)

func (e *VehicleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehicleType(s)
	case string:
		*e = VehicleType(s)
	default:
		return fmt.Errorf("unsupported scan type for VehicleType: %T", src)
	}
	return nil
}

type NullVehicleType struct {
	VehicleType VehicleType
	Valid       bool // Valid is true if VehicleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehicleType) Scan(value interface{}) error {
	if value == nil {
		ns.VehicleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehicleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehicleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehicleType), nil
}

type WateringPlanStatus string

const (
	WateringPlanStatusPlanned     WateringPlanStatus = "planned"
	WateringPlanStatusActive      WateringPlanStatus = "active"
	WateringPlanStatusCanceled    WateringPlanStatus = "canceled"
	WateringPlanStatusFinished    WateringPlanStatus = "finished"
	WateringPlanStatusNotcompeted WateringPlanStatus = "not competed"
	WateringPlanStatusUnknown     WateringPlanStatus = "unknown"
)

func (e *WateringPlanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WateringPlanStatus(s)
	case string:
		*e = WateringPlanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WateringPlanStatus: %T", src)
	}
	return nil
}

type NullWateringPlanStatus struct {
	WateringPlanStatus WateringPlanStatus
	Valid              bool // Valid is true if WateringPlanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWateringPlanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WateringPlanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WateringPlanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWateringPlanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WateringPlanStatus), nil
}

type WateringStatus string

const (
	WateringStatusGood        WateringStatus = "good"
	WateringStatusModerate    WateringStatus = "moderate"
	WateringStatusBad         WateringStatus = "bad"
	WateringStatusUnknown     WateringStatus = "unknown"
	WateringStatusJustwatered WateringStatus = "just watered"
)

func (e *WateringStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WateringStatus(s)
	case string:
		*e = WateringStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WateringStatus: %T", src)
	}
	return nil
}

type NullWateringStatus struct {
	WateringStatus WateringStatus
	Valid          bool // Valid is true if WateringStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWateringStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WateringStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WateringStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWateringStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WateringStatus), nil
}

type Region struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Geometry  *geos.Geom
}

type Sensor struct {
	ID                     string
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	Status                 SensorStatus
	Latitude               float64
	Longitude              float64
	Geometry               *geos.Geom
	Provider               *string
	AdditionalInformations []byte
}

type SensorDatum struct {
	ID        int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Data      []byte
	SensorID  string
}

type Tree struct {
	ID                     int32
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	TreeClusterID          *int32
	SensorID               *string
	PlantingYear           int32
	Species                string
	Number                 string
	Latitude               float64
	Longitude              float64
	WateringStatus         WateringStatus
	Geometry               *geos.Geom
	Description            *string
	Provider               *string
	AdditionalInformations []byte
	LastWatered            pgtype.Timestamp
}

type TreeCluster struct {
	ID                     int32
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	WateringStatus         WateringStatus
	LastWatered            pgtype.Timestamp
	MoistureLevel          float64
	Address                string
	Description            string
	Archived               bool
	SoilCondition          TreeSoilCondition
	Latitude               *float64
	Longitude              *float64
	Geometry               *geos.Geom
	RegionID               *int32
	Name                   string
	Provider               *string
	AdditionalInformations []byte
}

type TreeClusterWateringPlan struct {
	TreeClusterID  int32
	WateringPlanID int32
	ConsumedWater  float64
}

type UserWateringPlan struct {
	UserID         pgtype.UUID
	WateringPlanID int32
}

type Vehicle struct {
	ID                     int32
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	NumberPlate            string
	Description            string
	WaterCapacity          float64
	Type                   VehicleType
	Status                 VehicleStatus
	Model                  string
	DrivingLicense         DrivingLicense
	Height                 float64
	Length                 float64
	Width                  float64
	Weight                 float64
	Provider               *string
	AdditionalInformations []byte
	ArchivedAt             pgtype.Timestamp
}

type VehicleWateringPlan struct {
	VehicleID      int32
	WateringPlanID int32
}

type WateringPlan struct {
	ID                     int32
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	Date                   pgtype.Date
	Description            string
	Status                 WateringPlanStatus
	Distance               *float64
	TotalWaterRequired     *float64
	CancellationNote       string
	GpxUrl                 *string
	RefillCount            int32
	Duration               float64
	Provider               *string
	AdditionalInformations []byte
}
