// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ArchiveTreeCluster(ctx context.Context, id int32) (int32, error)
	ArchiveVehicle(ctx context.Context, arg *ArchiveVehicleParams) (int32, error)
	CalculateGroupedCentroids(ctx context.Context, dollar_1 []int32) (string, error)
	CalculateTreesCentroid(ctx context.Context, treeClusterID *int32) (string, error)
	CreateRegion(ctx context.Context, arg *CreateRegionParams) (int32, error)
	CreateSensor(ctx context.Context, arg *CreateSensorParams) (string, error)
	CreateTree(ctx context.Context, arg *CreateTreeParams) (int32, error)
	CreateTreeCluster(ctx context.Context, arg *CreateTreeClusterParams) (int32, error)
	CreateVehicle(ctx context.Context, arg *CreateVehicleParams) (int32, error)
	CreateWateringPlan(ctx context.Context, arg *CreateWateringPlanParams) (int32, error)
	DeleteAllTreeClusterFromWateringPlan(ctx context.Context, wateringPlanID int32) error
	DeleteAllUsersFromWateringPlan(ctx context.Context, wateringPlanID int32) error
	DeleteAllVehiclesFromWateringPlan(ctx context.Context, wateringPlanID int32) error
	DeleteRegion(ctx context.Context, id int32) error
	DeleteSensor(ctx context.Context, id string) error
	DeleteTree(ctx context.Context, id int32) (int32, error)
	DeleteTreeCluster(ctx context.Context, id int32) (int32, error)
	DeleteVehicle(ctx context.Context, id int32) (int32, error)
	DeleteWateringPlan(ctx context.Context, id int32) (int32, error)
	FindNearestTree(ctx context.Context, arg *FindNearestTreeParams) (*Tree, error)
	GetAllArchivedVehicles(ctx context.Context) ([]*Vehicle, error)
	GetAllLatestSensorDataByTreeClusterID(ctx context.Context, id int32) ([]*SensorDatum, error)
	GetAllRegions(ctx context.Context, arg *GetAllRegionsParams) ([]*Region, error)
	GetAllRegionsCount(ctx context.Context) (int64, error)
	GetAllSensorDataByID(ctx context.Context, sensorID string) ([]*SensorDatum, error)
	GetAllSensors(ctx context.Context, arg *GetAllSensorsParams) ([]*Sensor, error)
	GetAllSensorsCount(ctx context.Context, provider interface{}) (int64, error)
	GetAllTreeClusterRegionsWithWateringPlanCount(ctx context.Context) ([]*GetAllTreeClusterRegionsWithWateringPlanCountRow, error)
	GetAllTreeClusterWateringPlanByID(ctx context.Context, wateringPlanID int32) ([]*TreeClusterWateringPlan, error)
	GetAllTreeClusters(ctx context.Context, arg *GetAllTreeClustersParams) ([]*TreeCluster, error)
	GetAllTrees(ctx context.Context, arg *GetAllTreesParams) ([]*Tree, error)
	GetAllTreesCount(ctx context.Context, arg *GetAllTreesCountParams) (int64, error)
	GetAllUserWateringPlanCount(ctx context.Context) (int64, error)
	GetAllVehicles(ctx context.Context, arg *GetAllVehiclesParams) ([]*Vehicle, error)
	GetAllVehiclesByType(ctx context.Context, arg *GetAllVehiclesByTypeParams) ([]*Vehicle, error)
	GetAllVehiclesByTypeCount(ctx context.Context, arg *GetAllVehiclesByTypeCountParams) (int64, error)
	GetAllVehiclesByTypeWithArchived(ctx context.Context, arg *GetAllVehiclesByTypeWithArchivedParams) ([]*Vehicle, error)
	GetAllVehiclesByTypeWithArchivedCount(ctx context.Context, arg *GetAllVehiclesByTypeWithArchivedCountParams) (int64, error)
	GetAllVehiclesCount(ctx context.Context, provider interface{}) (int64, error)
	GetAllVehiclesWithArchived(ctx context.Context, arg *GetAllVehiclesWithArchivedParams) ([]*Vehicle, error)
	GetAllVehiclesWithArchivedCount(ctx context.Context, provider interface{}) (int64, error)
	GetAllVehiclesWithWateringPlanCount(ctx context.Context) ([]*GetAllVehiclesWithWateringPlanCountRow, error)
	GetAllWateringPlans(ctx context.Context, arg *GetAllWateringPlansParams) ([]*WateringPlan, error)
	GetAllWateringPlansCount(ctx context.Context, provider interface{}) (int64, error)
	GetLatestSensorDataByID(ctx context.Context, sensorID string) (*SensorDatum, error)
	GetLinkedTreesByTreeClusterID(ctx context.Context, id int32) ([]*Tree, error)
	GetRegionById(ctx context.Context, id int32) (*Region, error)
	GetRegionByName(ctx context.Context, name string) (*Region, error)
	GetRegionByPoint(ctx context.Context, stGeomfromtext interface{}) (*Region, error)
	GetRegionByTreeClusterID(ctx context.Context, id int32) (*Region, error)
	GetSensorByID(ctx context.Context, id string) (*Sensor, error)
	GetSensorByStatus(ctx context.Context, status SensorStatus) ([]*Sensor, error)
	GetSensorByTreeID(ctx context.Context, id int32) (*Sensor, error)
	GetTotalConsumedWater(ctx context.Context) (int64, error)
	GetTreeByCoordinates(ctx context.Context, arg *GetTreeByCoordinatesParams) (*Tree, error)
	GetTreeByID(ctx context.Context, id int32) (*Tree, error)
	GetTreeBySensorID(ctx context.Context, sensorID *string) (*Tree, error)
	GetTreeClusterByID(ctx context.Context, id int32) (*TreeCluster, error)
	GetTreeClusterByTreeID(ctx context.Context, id int32) (*TreeCluster, error)
	GetTreeClustersByWateringPlanID(ctx context.Context, wateringPlanID int32) ([]*TreeCluster, error)
	GetTreeClustersCount(ctx context.Context, arg *GetTreeClustersCountParams) (int64, error)
	GetTreesByIDs(ctx context.Context, dollar_1 []int32) ([]*Tree, error)
	GetTreesBySensorIDs(ctx context.Context, dollar_1 []string) ([]*Tree, error)
	GetTreesByTreeClusterID(ctx context.Context, treeClusterID *int32) ([]*Tree, error)
	GetTreesClustersByIDs(ctx context.Context, dollar_1 []int32) ([]*TreeCluster, error)
	GetUsersByWateringPlanID(ctx context.Context, wateringPlanID int32) ([]uuid.UUID, error)
	GetVehicleByID(ctx context.Context, id int32) (*Vehicle, error)
	GetVehicleByPlate(ctx context.Context, numberPlate string) (*Vehicle, error)
	GetVehicleByWateringPlanID(ctx context.Context, arg *GetVehicleByWateringPlanIDParams) (*Vehicle, error)
	GetWateringPlanByID(ctx context.Context, id int32) (*WateringPlan, error)
	InsertSensorData(ctx context.Context, arg *InsertSensorDataParams) error
	LinkTreesToTreeCluster(ctx context.Context, arg *LinkTreesToTreeClusterParams) error
	RemoveTreeClusterLocation(ctx context.Context, id int32) error
	SetSensorLocation(ctx context.Context, arg *SetSensorLocationParams) error
	SetTreeClusterLocation(ctx context.Context, arg *SetTreeClusterLocationParams) error
	SetTreeClusterToWateringPlan(ctx context.Context, arg *SetTreeClusterToWateringPlanParams) error
	SetTreeLocation(ctx context.Context, arg *SetTreeLocationParams) error
	SetUserToWateringPlan(ctx context.Context, arg *SetUserToWateringPlanParams) error
	SetVehicleToWateringPlan(ctx context.Context, arg *SetVehicleToWateringPlanParams) error
	UnlinkSensorIDFromTrees(ctx context.Context, sensorID *string) error
	UnlinkTreeClusterID(ctx context.Context, treeClusterID *int32) ([]int32, error)
	UpdateRegion(ctx context.Context, arg *UpdateRegionParams) error
	UpdateSensor(ctx context.Context, arg *UpdateSensorParams) error
	UpdateTree(ctx context.Context, arg *UpdateTreeParams) error
	UpdateTreeCluster(ctx context.Context, arg *UpdateTreeClusterParams) error
	UpdateTreeClusterID(ctx context.Context, arg *UpdateTreeClusterIDParams) error
	UpdateTreeClusterWateringPlan(ctx context.Context, arg *UpdateTreeClusterWateringPlanParams) error
	UpdateTreeGeometry(ctx context.Context, arg *UpdateTreeGeometryParams) error
	UpdateVehicle(ctx context.Context, arg *UpdateVehicleParams) error
	UpdateWateringPlan(ctx context.Context, arg *UpdateWateringPlanParams) error
}

var _ Querier = (*Queries)(nil)
